### ISSUE TITLE
When i run node index.js i got error can not find module index.js ?

### ISSUE THREAD

**Issue by useralive003** [cezerin/cezerin#142]
module.js:471
    throw err;
    ^

Error: Cannot find module 'F:\cezerin\index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

can you help me ou

**Comment by restmount** [comment]
Dear @useralive003,
Please click to Watch or Star this repository. 
In two weeks I will 
- test on windows 
- deliver Docker image
- write setup doc

Thanks for interest!

**Comment by useralive003** [comment]
i did not get you , what are you trying to say

**Comment by restmount** [comment]
In couple weeks project will be ready to start on local environment.

**Comment by useralive003** [comment]
now i cant use this ?

**Comment by restmount** [comment]
Right now project are in active development and not stable.
Soon I will release a demo and in month or two we will have stable release.

**Comment by restmount** [comment]
Please follow this [step by step instructions](https://github.com/cezerin/cezerin/wiki/installation) to install.
