### ISSUE TITLE
Edit product variants

### ISSUE THREAD

**Issue by restmount** [cezerin/cezerin#161]

**Comment by sonufrienko** [comment]
@restmount, on Gollos we has simple design

![variants](https://cloud.githubusercontent.com/assets/16773498/24994161/48d3dca8-2032-11e7-980b-1b9c2fed4ed6.png)

Click on cell and type new value.

**Comment by restmount** [comment]
Thanks @sonufrienko !
I like your grid.

![v](https://cloud.githubusercontent.com/assets/8514556/25003967/96771f1a-205a-11e7-8aaa-d5ec9aa20fd0.png)
