### ISSUE TITLE
Bug with build on production

### ISSUE THREAD

**Issue by sonufrienko** [cezerin/cezerin#244]
1. I use pm2 to start process
2. npm run build
3. empty page

Is it problem with watch on pm2 process file?

**Comment by stunjiturner** [comment]
i built locally and get a empty page, with page not found error

**Comment by restmount** [comment]
Hi @stunjiturner, 
do you connect to MongoDB? To start you additionally need 3 steps:
1. connect mongodb on **config/server.js**
2. add init data to mongodb (token, settings, core pages, etc)
3. setup STMP to send auto login email (on **config/server.js** or in **mongodb**)

https://github.com/cezerin/cezerin/wiki/installation

**Comment by stunjiturner** [comment]
how does one name and create the mongodb database, so that i can do the inserts?

**Comment by restmount** [comment]
@stunjiturner 
step 1: /config/server.js - specify **mongodbServerUrl**
step 2: setup SMTP server to send you login link
- you can do this in /config/server.js - **smtpServer**
- or in mongodb
_db.emailSettings.insert({
host: 'smtp.domain.com',
port: 465,
user: 'smtpUser',
  pass: 'smtpPass',
  from_name: 'Store',
  from_address: 'email@domain.com'
});_

If you don't have smtp, you can get https://www.mailgun.com/ for free.

**Comment by restmount** [comment]
Also, latest cezerin version (0.18.0) use NPM v5.

**Comment by restmount** [comment]
@sonufrienko you need to upgrade to NPM v5
