### ISSUE TITLE
Product Images Can't Be Deleted

### ISSUE THREAD

**Issue by stunjiturner** [cezerin/cezerin#265]
There are two issues 
when a product image is added, it does not show?
when a product image is added in the admin section it cannot be deleted.

src="http://0.0.0.0:3000/static/products/5942bba50865268167a145ea/340/goat_red_test.png" 

the source omg URL seems to malformed compared to the actual folder structure of the image uploaded. /static/products/5942bba50865268167a145ea/goat_red_test.png should exist? but a number /340/ is in front? when i had a image to a category a number is placed in the URL again between /categories/ and the / [image name]

**Comment by stunjiturner** [comment]
I realize that the product_id is being inserted into the URL in images.getImages(), but the folder structure on creation is not set like that.

**Comment by restmount** [comment]
@stunjiturner thanks!
