### ISSUE TITLE
Brand Needs to be a separate collection with relationship to product.

### ISSUE THREAD

**Issue by stunjiturner** [cezerin/cezerin#266]
We Need Brand Model

**Comment by restmount** [comment]
@stunjiturner 
please, try product attributes. You can add a brand as an attribute. Attributes allow filtering products. It's more flexible.

**Comment by stunjiturner** [comment]
i have tried them, under attribute name I put Brand and then attribute value i  put Apple? is there any documentation for product attributes

**Comment by restmount** [comment]
@stunjiturner sorry, docs will be soon.

You're right.
Attribute name: Brand
Attribute value: Apple

And you'll see it in product filter.

**Comment by jrsantur** [comment]
Where is the database model?
