### ISSUE TITLE
Product Bundle Feature Wanted

### ISSUE THREAD

**Issue by lfurzewaddock** [cezerin/cezerin#267]
One of my requirements, currently not present and not on your road map is product bundles.

Bundles would be products made up of other products. The database could get a new lookup table (n to n), linked to a table holding the parent product id and child product id(s). This would allow for there to be bundles of bundles in theory.

The benefit of this approach is that little needs to change in the current public facing businesses logic as product bundles are just another product, so could be added to the shopping cart, included in tax calculations based upon address details and virtually everything else you can do with a standard product. 

Most of the additional development work would be concerned with the Admin UX to enable admins to manage/report product bundles and in the public customer facing UX, to display the parent/child relationship. 

For example, a product bundle could have its own name, price, description and image, but would also list the products it is comprised of. Later, more advanced options could be added to show/hide bundle price saving, show/hide child product prices, show/hide a link to 'other bundles featuring this product', similar to 'related products', etc.

What do you think?

**Comment by restmount** [comment]
@lfurzewaddock good idea.
But first, we have to add payments and other features with first priority.
