### ISSUE TITLE
babel-cli installed globally required by npm compile scripts?

### ISSUE THREAD

**Issue by lfurzewaddock** [cezerin/cezerin#268]
Should the babel-cli package be installed globally to support the following npm scripts, before running the build scripts for the first time?

```    
"compile:dev": "babel src -d dist --watch & babel themes/current/src -d themes/current/dist --watch",
"compile": "babel src -d dist --quiet",
```

**Comment by restmount** [comment]
No, babel-cli is local package.
You don't need any global package.
