### ISSUE TITLE
images and manifest.json not copied to public from themes

### ISSUE THREAD

**Issue by lfurzewaddock** [cezerin/cezerin#271]
```
$ npm install
$ npm run build:dev
$ npm run start:dev
```

Above steps do no copy 'images' directory including contents and manifest.json file...

```
\themes\current\assets\images
\themes\current\assets\manifest.json
```

...to destination;

```
\public\assets\images
\public\assets\manifest.json
```

**Comment by restmount** [comment]
@lfurzewaddock 
to copy theme assets try this:

- ```npm run theme:copy```
just copy /themes/current/asses/ to /public/assets/

- ```npm run theme:build:prod```
copy assets and build theme

- ```npm run build```
copy assets and build all project
