### ISSUE TITLE
Product image 404 - src path broken by 'width' variable

### ISSUE THREAD

**Issue by lfurzewaddock** [cezerin/cezerin#272]
On the home page a newly created product with an image successfully uploaded via the admin area fails to display with a 404 error.

The simple fix is below, however I suspect this 'width' variable is required by other functionality;

themes\current\src\lib\helper.js:
line 24:

```
//const thumbnailUrl = originalUrl.substring(0, pos) + `/${width}/` + originalUrl.substring(pos + 1);
const thumbnailUrl = originalUrl.substring(0, pos) + `/` + originalUrl.substring(pos + 1);
```

**Comment by restmount** [comment]
@lfurzewaddock 
``` `/${width}/` ```
used to set thumbnail width, like this image-path/400/file.png

You need to setup Nginx to create thumbnails dynamically.
Check docker-compose here: 
https://github.com/cezerin/docker-cezerin/blob/master/compose/docker-compose.yml
