### ISSUE TITLE
all in one docker-compose.yml file?

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#293]
Hi, someone know if the project have an docker-compose.yml file for easy deploy an test it?

thanks in advance,

**Comment by restmount** [comment]
Hi @roboto-cloud 
I use this image https://github.com/cezerin/docker-cezerin/blob/master/images/0.26.0/Dockerfile
It contains mongodb, nginx and nodejs inside.

```
docker run -d --name store \
-v /var/www/cezerin/db:/data/db \
-v /var/www/cezerin/public/content:/var/www/cezerin/public/content \
-p 80:80 \
cezerin/cezerin:latest
```

**Comment by restmount** [comment]
You can initialize DB with default data:
https://github.com/cezerin/cezerin/wiki/installation#add-default-data-mongodb

Also, check config file at /config/server.js

**Comment by roboto-cloud** [comment]
Hi @restmount, thanks for the tips, I tried initializing on docker but don't get successes using docker...

I put the mongo default data inside .json file and run inside docker:
**mongoimport --file default.json**
**mongoimport --file indexes.json**

but don't work..

do you tell me how dump this data?

thanks in advance,
