### ISSUE TITLE
Pure 404 for files

### ISSUE THREAD

**Issue by sonufrienko** [cezerin/cezerin#296]
If URL includes file extension page should return pure 404 (empty response).
Example:
```
https://demo.gollos.com/no-file.png
```

**Comment by orvi2014** [comment]
Hello, can I work on this one ?

**Comment by restmount** [comment]
@orvi2014 
yes, please.
Where should we check this URL? Nginx or Node?

**Comment by orvi2014** [comment]
It will be good idea to check URL in Nginx and serve the custom error page  from there.

**Comment by restmount** [comment]
Okay, let's do it!

**Comment by orvi2014** [comment]
Well do you guys use `slack` ? It would be better idea to keep our conversation there.

**Comment by restmount** [comment]
Sure, welcome https://cezerin.slack.com

**Comment by restmount** [comment]
Done with Express.js
