### ISSUE TITLE
Cezerin installation 

### ISSUE THREAD

**Issue by TheBackendGuy** [cezerin/cezerin#297]
I come from python and PHP background so please excuse if I'm asking elementary questions. 

I followed the installation steps from cerezin wiki 
When I run the application I see a page with no images or products 
(I do have a database called shop with default data loaded in and connected to) 

It seems like /assets folder returns 404 for some reason.
The index.js file under /dist
Has the following line 
```
app.get('assets/*',function (request,Res){
    res.status(404).end();
}):
```

Does this mean /assets are to return 404s? 

Also after npm run build I don't see an assets folder under /public
(Same after running npm run theme:copy and npm run theme:build:dev or prod)

Any help to get it running is appreciated :)

**Comment by negati-ve** [comment]
I was able to get it to work by rebuilding.. you can close this. 
Thanks !

**Comment by restmount** [comment]
@TheBackendGuy 
Try ```npm run build```

Also, check updated docs - https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

**Comment by arhyth** [comment]
@TheBackendGuy did you get your installation sorted? I'm also stuck in the same page. Also, I'm confused because some of the commands in the Dockerfile is already "solved" by the git repo, is the Docker process an alternative to the repo clone process?

**Comment by restmount** [comment]
@arhyth @TheBackendGuy 
If installation complete right, you'll see store page with no products, no images and without a logo. At this MongoDB have only basic data. After installation, you can go to dashboard and add whatever you need.

But you right, we definitely need to prefill database :-)

**Comment by restmount** [comment]
@TheBackendGuy 
Where you stuck on? I will help you.

**Comment by arhyth** [comment]
my first try was really bare like not even text formatted bare. :) finally understood the installation process a bit, was able to get running and connect to this page (my admin page is the same, "Page not found"). both from docker method and from usual method. but how do i get from here to one that looks like the demo? the dashboard you refer to, is that a separate page? thanks a lot. 

![screenshot from 2017-11-16 23 49 42](https://user-images.githubusercontent.com/28768384/32902412-4a366e52-cb2d-11e7-9692-3f79e2ea3a0b.png)

**Comment by restmount** [comment]
@arhyth 
Dashboard location - /admin
When you request a /admin Nginx gives you a static HTML page generated by WebPack.

What url  return 404? Index?
If index - go to https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md
**3. Add default data**
_db.pages.insertMany([ ...._

**Comment by vladmee** [comment]
I have the same problem as @TheBackendGuy. There is no assets folder in the public directory after running all the commands. All assets return 404, and trying to get .js files like sw.js from public acts like trying to access a route.

Please find attached a screenshot of my console errors on the homepage.
<img width="1278" alt="screen shot 2017-11-21 at 00 23 00" src="https://user-images.githubusercontent.com/5617700/33044794-fde3a6fe-ce52-11e7-8340-f3da0c6190c7.png">

**Comment by restmount** [comment]
@vladmee 
Seems you install from GitHub source. It's quicker to start with Docker.
Check Docker setup process: https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

Right now all your request go to Node.js instead of Nginx.

**Comment by vladmee** [comment]
@restmount 
Thank you, it seems that the current setup requires Nginx, so I went with the Docker path. I managed to make it work partially. 

I never used Docker before and there are many missing links in your current docs. Docker comes without an editor, so before being able to run `nano server.js` you need to actually install nano: `apt-get install nano`

While trying to add the default data, the `mongo` command cannot be found through the cezerin bash. I've tried both, trying to connect Docker with the local mongo setup and setting up a mongo image through Docker. None worked.

This is the error I'm getting while running the setup docker run command:
<img width="567" alt="screen shot 2017-11-21 at 20 18 22" src="https://user-images.githubusercontent.com/5617700/33089716-2c2b1d1a-cefa-11e7-833c-c123ec788b5f.png">

**Comment by restmount** [comment]
@vladmee 
Pls, send me you _docker run..._ command.
Also check **mongodbServerUrl** in **/config/server.js**.

**Comment by vladmee** [comment]
@restmount 
**mongodbServerUrl: 'mongodb://127.0.0.1:27017/shop'** (seems right)

This is the command I run:
**docker run \
      --name cezerin \
      -v /data/db:/data/db \
      -p 3000:80 \
      cezerin/cezerin:latest**

**/data/db** exists on my local machine and I've exposed it to Docker.

**Comment by restmount** [comment]
@vladmee 
1. check permission of **/data/db** folder.
2. if MongoDB exists before setup, check MongoDB listening on 127.0.0.1

**Comment by vladmee** [comment]
@restmount
Same issue...

I've set **777** permissions to **/data/db** folder.

I've set **bind_ip = 127.0.0.1** in **mongod.conf**
<img width="737" alt="screen shot 2017-11-21 at 21 53 37" src="https://user-images.githubusercontent.com/5617700/33095277-c171caca-cf0b-11e7-86c6-9ea9580d8544.png">

**Comment by negati-ve** [comment]
Thanks to @TheBackendGuy,
Commented this out :
```
// app.get('/assets/*', (req, res) => {
//   res.status(404).end();
// });
```
Also had to rename path to js bundles.
Works now!

**Comment by ipnuds** [comment]
I have problem while installing using docker 
first i try use this 

`docker run \
      --name cezerin \
      -v /var/www/cezerin/db:/data/db \
      -p 3000:80 \
      cezerin/cezerin:latest`

![cez1](https://user-images.githubusercontent.com/5379215/33590364-5c8f1e68-d9b1-11e7-90eb-8ba2e08bdea0.PNG)

the result was like that.  when i open the brower the web not come out.
when i try nano to server.js it's write that nano command not found.  then someone said to install editor but when I use apt-get it said that apt-get command not found either.

then i tried to build from dockerfile. then i have to images

![images](https://user-images.githubusercontent.com/5379215/33590450-0e6feeaa-d9b2-11e7-8cc6-d1fbab4c114d.PNG)

then i tried this command
`docker run -d --name store \
-v /var/www/cezerin/db:/data/db \
-v /var/www/cezerin/public/content:/var/www/cezerin/public/content \
-v /var/www/cezerin/config/server.js:/var/www/cezerin/config/server.js \
-p 80:80 \
cezerin`

the result

![docker-1](https://user-images.githubusercontent.com/5379215/33590480-3d855ff4-d9b2-11e7-86b0-64747e127633.PNG)

when i use this command 

`docker run \
      --name store\
      -v /var/www/cezerin/db:/data/db \
      -p 3000:80 \
      cezerin/cezerin:latest`

the result 

![cez2](https://user-images.githubusercontent.com/5379215/33590501-5dfbdde4-d9b2-11e7-9e9b-a046ee7e50d6.png)

could someone tell me the right procedure to install it and how to run?
i'm new in docker
thanks

**Comment by restmount** [comment]
@ipnuds 
Ohhh crap...
Docker auto build tagget latest another build.

use this:
```
docker run --name store -p 3000:80 cezerin/cezerin:0.28.0
```

**Comment by restmount** [comment]
Just pushed 
```
cezerin/cezerin:latest
```

now you can use
```
docker run --name store -p 3000:80 cezerin/cezerin:latest
```

**Comment by ipnuds** [comment]
@restmount thanks it's working now : )

I new in docker. I still don't understand the workflow how to develop in docker.
if I want to change the code how to access the source code. in the conventional way we just clone the project then start modify the code, but how we do that in docker?
thx

**Comment by restmount** [comment]
@ipnuds 
check this: https://github.com/cezerin/cezerin/blob/master/docs/developer.md

workflow:
1. clone - ```git clone https://github.com/cezerin/cezerin.git cezerin```
2. install and build - ```npm i && npm run build```
3. ```npm run build:dev``` (with watch) and leave terminal open
4. run docker and map to cloned folder
```
docker run \
      --name cezerin \
      -v /var/www/cezerin/db:/data/db \
      -v /var/www/cezerin/cezerin:/var/www/cezerin \
      -p 3000:80 \
      cezerin/cezerin:latest
```

5. after modifying files, ```build:dev``` will rebuild project

This docker container gives you:
- MongoDB
- Nginx to serve static files and resize images
- NodeJS

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
