### ISSUE TITLE
handling token and admin access way?

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#298]
Hi, someone know how handling token for get admin access on the Dashboard?
**every token what I get from here let me see the dashboard but not make changes...**
https://www.jsonwebtoken.io/

**In the Demo store I don't see any product...** 
![screenshot from 2017-11-04 18-43-14](https://user-images.githubusercontent.com/32390825/32407957-805edbe6-c190-11e7-81b2-8c9c17565e41.png)

Thanks in advance,

**Comment by negati-ve** [comment]
have you added default data to your database?
see https://github.com/cezerin/cezerin/wiki/installation

**Comment by roboto-cloud** [comment]
@negati-ve not yet..
I want to know how add default data and manage admin area (token)

Regards,

**Comment by restmount** [comment]
@roboto-cloud 
Check new docs: https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

**Comment by restmount** [comment]
To setup tokens, you need:
1. set **jwtSecretKey** in /config/server.js
2. add token details to MongoDB
3. setup **mail server** (SMTP) to send you a login link

**Comment by restmount** [comment]
@roboto-cloud 
still have a problem?

**Comment by roboto-cloud** [comment]
Hi @restmount, yes I still have this problem, don't get admin access...
can you help me please :)

**Comment by adilfaiz001** [comment]
> To setup tokens, you need:
> 
> 1. set **jwtSecretKey** in /config/server.js
> 2. add token details to MongoDB
> 3. setup **mail server** (SMTP) to send you a login link

how to add access tokens to mongo.
