### ISSUE TITLE
no mail after follow the documentation

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#305]
Hi @restmount, no possible login after follow the guide step by step, attach an capture.
![screenshot from 2017-11-14 02-35-47](https://user-images.githubusercontent.com/32390825/32758507-0d7b8f00-c8e5-11e7-9fed-3f8f008d6dc8.png)

Regards,

**Comment by restmount** [comment]
Hi @roboto-cloud 
Please, go to Step 2 https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md
Cezerin is passwordless. So you need a mail server. The dashboard will send you token - link to login.

**Comment by roboto-cloud** [comment]
Hi @restmount, true I use the docker deploy version with all this information:
-v /var/www/cezerin/config/server.js:/var/www/cezerin/config/server.js \

This issue was solver because I use SMTP with STARTTLS on port 587, so my final config is:

```
  smtpServer: {
    host: 'smtp.example.com',
    port: 587,
    secure: false,
    user: 'hello@example.com',
    pass: 'password',
    fromName: 'Cezerin Store',
    fromAddress: 'hello@example.com'
  },

```

Regards,
