### ISSUE TITLE
error: 504 (Gateway Time-out)

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#306]
Hi @restmount do you know who fix it?
after add a product, the browser get white.. here a capture:

Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

![screenshot from 2017-11-14 10-53-44](https://user-images.githubusercontent.com/32390825/32773636-1da111a8-c92a-11e7-8e74-900fe3bddece.png)

**Comment by restmount** [comment]
@roboto-cloud 
hm... formatCurrency...
please, check currency settings

![451513](https://user-images.githubusercontent.com/8514556/32774023-b0c27a7c-c933-11e7-80cc-3c4c29a01352.png)

**Comment by roboto-cloud** [comment]
@restmount awesome!
this project is amazing, congrats!

I set up general info and your like a charm! thanks :100: 

Regards,

**Comment by restmount** [comment]
@roboto-cloud 
:blush: It's a pleasure to hear
