### ISSUE TITLE
Clear disposable folders for Docker builds

### ISSUE THREAD

**Issue by pepijnblom** [cezerin/cezerin#307]
Hi, I have been building Docker images for your project and I've been trying to optimise them using multi-stage builds on Alpine and one process per container. I've gotten most of it done, but there's just one thing that's stopping me now: I can't figure out which files are required and which can be thrown away. The build process is a bit unclear. I asked our frontender to have a look and he couldn't tell me right away either so I think that needs a bit of work.

Ideally I would like to see the disposable code/files in a folder in the root of the project and the rest of the code in a dist folder or something. That way you can just do a `COPY --from=0 ./build/ /app/` after the build stage and leave all the other stuff. The public folder should probably also be in dist as that's the document root.

I have the project down to the following three images:
- 8MB nginx
- 106MB mongodb
- 133MB node/js

I also have a working docker-compose.yml file and I'll be starting on Kubernetes & Docker Swarm after that.

**Comment by sonufrienko** [comment]
@pepijnblom 
Not clearly understand what you want.
In node.js container, you can copy cezerin and map folders:
- /theme
- /config
- /public/content
alll other files can be upgradeable.

I also tried a docker-compose and swarm to run cezerin.

**Comment by pepijnblom** [comment]
I have everything working, that's not the problem. It runs beautifully :)
I'm just trying to clean up the containers by removing anything that's not necessary.
Once that's done I'll share all the files.

I just have this feeling like I'm copying lots of useless stuff to the containers. The whole build & compile process takes quite a while, that must result in lots of data that can be thrown away.

Ideally I would do something like this, this is *one* Dockerfile. I'm not sure if you are familiar with [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).

```docker
FROM alpine:3.6 AS builder
ARG CEZERIN_VERSION=0.27.0
WORKDIR /app
RUN apk add --no-cache git ca-certificates libressl && \
    git clone https://github.com/graciousstudios/cezerin.git . && \
    git checkout v${CEZERIN_VERSION} && \
    npm install && \
    npm run build

FROM keymetrics/pm2:8
EXPOSE 3000
WORKDIR /app/
CMD [ "pm2-docker", "process.json" ]
COPY --from=builder /app/dist/ /app/
```

So I build in the first stage and everything that is absolutely 100% necessary ends up in /app/dist. Then in the second stage (this is one Dockerfile) I copy over the /app/dist/ folder to /app/ and leave behind everything else. Then you have a pretty optimised & clean container.

**Comment by restmount** [comment]
@pepijnblom 

> theme/assets/css has scss files in it

yes, theme/assets/scss will be better

> why is there a dist folder in theme

Cezerin uses server-side rendering, so we need to keep /dist/ to execute files on node.js.

> it has a separate node_modules folder 

/theme is a local package. The idea is to build a theme like an independent package with own dependencies.

> Personally I would even break admin, api and store up into their own containers so they can be scaled separately from each other.

And you are absolutely right here. This was my first build, but this adds complexity to develop. On high loaded apps this will be necessary. In future will think about separate it.

> You will also want to upload resized product images to cloud storage, you will run into problems otherwise scaling horizontally. You do not want to keep copies of all images on each instance and writing in your container is a bad idea.

We use Nginx to resize images dynamically. I use volume to store files, like this
```
-v /var/www/content:/var/www/cezerin/public/content
```

**Comment by sonufrienko** [comment]
I also use volumes to store content, config files and theme on host.

```
-v /var/www/db:/data/db
-v /var/www/config:/var/www/cezerin/config
-v /var/www/content:/var/www/cezerin/public/content
```
