### ISSUE TITLE
No Css  on site

### ISSUE THREAD

**Issue by Moshikol** [cezerin/cezerin#308]
i followed the gtsg  and when i use  npm start this site come up without any css or   ##stylesheets
what should i do?
windows 10 machine
npm ver : 5.5.1

![image](https://user-images.githubusercontent.com/19548879/33080010-b2987be2-cedf-11e7-9757-60924a50f9bf.png)

**Comment by restmount** [comment]
Hi @Moshikol,
1. what is your assets URL?
2. on which port you run container?

**Comment by Moshikol** [comment]
what do you mean by container?

**Comment by restmount** [comment]
https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md
you follow this guide?

**Comment by restmount** [comment]
**Page not found** - seems you messed **step 3**

**Comment by Moshikol** [comment]
docker keep crashing when i open it  so you say thats the problem ?

**Comment by restmount** [comment]
@Moshikol 
Look, if you setup Cezerin with Docker, then all static files served by Nginx.
To setup Cezerin without Nginx you need to configure node.js to serve static. I prefer Nginx.

> docker keep crashing when i open it so you say thats the problem ?

What's the error?

Can you run Docker on Linux or Mac?

**Comment by Moshikol** [comment]
`Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145


`

i googled it  and because of my windows version (Windows 10 Home) I cant run hyper-X and docker keep crashing

**Comment by restmount** [comment]
Sorry, I can't help. I am in love with Linux.

**Comment by Moshikol** [comment]
lol im trying to set it up in linux right now

**Comment by restmount** [comment]
Awesome!
Install Docker and comeback.

**Comment by Moshikol** [comment]
got docker up and running got other problem though 
i use mint linux distro and the latest ver of node and npm
![image](https://user-images.githubusercontent.com/19548879/33101195-f4bfa83e-cf1f-11e7-8189-f303996ebcae.png)

**Comment by restmount** [comment]
@Moshikol 
Go with this guide (Docker): https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

**Comment by dqhung215** [comment]
I also have same problem. I dont want to use Docker. I want to run it directly. So how to fix the static one? Thanks you!

**Comment by restmount** [comment]
@dqhung215 
in a week I will add an ability to run without Docker and Nginx.

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
