### ISSUE TITLE
Unable to start this project in local

### ISSUE THREAD

**Issue by vidyasagarg1222** [cezerin/cezerin#313]
Dear Team,

We are unable to start the project in local please suggest me how to run this project in local or any videos please provide me 

Thanks & regards,
GV Sagar
vidyasagar1222@gmail.com

**Comment by restmount** [comment]
@vidyasagarg1222 
What is your environment? Windows/Linux/Mac?

**Comment by vidyasagarg1222** [comment]
windows

**Comment by restmount** [comment]
@vidyasagarg1222 
The easier way is to [set up with Docker](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)

```
docker run --name cezerin -p 3000:80 cezerin/cezerin:latest
```
and open http://localhost:3000

**Comment by harshalyeole-tudip** [comment]
Hi @restmount ,
I have ubuntu environment and I am facing issue with `npm run build:dev`.
Actually nothing happens when I hit above command. So I need to use `npm run build` and then `npm start` which is for production environment.
Can you help me here?
Thank you.

**Comment by restmount** [comment]
@harshalyeole-tudip 
let's move to https://cezerin.slack.com

**Comment by harshalyeole-tudip** [comment]
@restmount 
Can you invite me?

**Comment by restmount** [comment]
what's your email

**Comment by harshalyeole-tudip** [comment]
Here's my email: harshal.yeole@tudip.nl

**Comment by restmount** [comment]
Sent.
Or click - https://join.slack.com/t/cezerin/shared_invite/enQtMjk4OTM0NTk5MjAyLWZkYjhlZTNlODc2NzdjMDMzNjI3MjExYmUyZDVjMmQ3YmUxYzM5YTUwYTNhZDYyZDU1MWFiYjhhYTI1NWUwNmM

**Comment by harshalyeole-tudip** [comment]
Thanks

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
