### ISSUE TITLE
I want add Chinese language file to this project

### ISSUE THREAD

**Issue by channingbox** [cezerin/cezerin#314]
What can I do,does this project have language file?

**Comment by restmount** [comment]
你好 @channingbox 

Yes, we have json file for each locale and each project section.

**Dashboard**: https://github.com/cezerin/cezerin/tree/master/locales/admin
**Store**: https://github.com/cezerin/cezerin/tree/master/locales/store
**Theme**: https://github.com/cezerin/cezerin/tree/master/theme/locales
