### ISSUE TITLE
create a docker-compose file

### ISSUE THREAD

**Issue by deresegetachew** [cezerin/cezerin#316]
That will make everyones life easier.

**Comment by restmount** [comment]
@deresegetachew 
Why not single dockerfile?
https://github.com/cezerin/docker-cezerin

**Comment by deresegetachew** [comment]
first and for most all you have to do will be **docker-compose up** and all the environment variables can be configured easily inside the docker-compose file; other than that you can run MongoDB and other dependencies you might have in the future in separate containers. This will all lead to a production ready step even from the get go. what do you think ?

**Comment by restmount** [comment]
:smile: this was my first setup with docker-compose. Then I created a single dockerfile.
You're right. Docker-compose will be better for production.

**Comment by restmount** [comment]
Available here https://github.com/cezerin/docker-cezerin
