### ISSUE TITLE
Running  by Cloning from Github is Broken

### ISSUE THREAD

**Issue by deresegetachew** [cezerin/cezerin#317]
i think you should mention in your docs on how to make the asset files available using node.js.

currently its broken as mentioned in previous issues. Please fix this.

**Comment by restmount** [comment]
Yes, you right. Soon I'll fix it.

**Comment by azmainamin** [comment]
I have the same issue. I cloned from GitHub, installed all npm packages and when I do the build, I get the following errors ( I just copied one):

ERROR in ./src/store/shared/containers/checkoutSuccess.js
Module not found: Error: Can't resolve 'theme' in 'C:\Users\aminm\git\billboard-marketplace\cezerin\src\store\shared\containers'
resolve 'theme' in 'C:\Users\aminm\git\billboard-marketplace\cezerin\src\store\shared\containers'

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
