### ISSUE TITLE
Why I cannot setup my local environment in mac

### ISSUE THREAD

**Issue by wozaisuzhou** [cezerin/cezerin#335]
Hi , 

I checkout the code and used the npm install and npm run build and npm start to launch the project. 
Mongodb is ready as well.   But I always get page is messed up ? 

Thanks

**Comment by channingbox** [comment]
又一位中国兄弟

**Comment by restmount** [comment]
@wozaisuzhou 
You need to add default data.
https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md step 3

**Comment by pawar-mahesh** [comment]
Its with docker. Can we setup it without docker. 
Nice work done!

**Comment by restmount** [comment]
@pawar-mahesh 
Will in a week.

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
