### ISSUE TITLE
Please provide a proper guide for installation without docker

### ISSUE THREAD

**Issue by naysumyat** [cezerin/cezerin#339]

**Comment by restmount** [comment]
Hi @naysumyat 
Will in a week.

**Comment by pawar-mahesh** [comment]
Though I installed it using the provided steps. But I am seeing assets loaded to localhost.
Any idea?

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)
