### ISSUE TITLE
seed data for preview

### ISSUE THREAD

**Issue by od3n** [cezerin/cezerin#341]

**Comment by arnaudcosson** [comment]
Hi, it could be very nice to have some products and Product Categories in the seeds examples

**Comment by sonufrienko** [comment]
Hi,
now we have 
```
npm run setup <email> <domain>
```
Script will add seed data, default settings, token and Indexes.

**Comment by mrhut10** [comment]
is there doc's to reflect this feature??? @sonufrienko
