### ISSUE TITLE
Unable to build on Windows/Linux

### ISSUE THREAD

**Issue by Premier** [cezerin/cezerin#344]
Hello,
i'm trying to build it on my computer Windows/Linux but after a lot of time it stops on building styles.

Performed tasks:
1) git clone
2) npm install
3) npm run build:dev

Can you help me please?
Tnx

**Comment by restmount** [comment]
Please, follow new [Getting Started](https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md)

**Comment by diggschauhan** [comment]
Sorry to reply on closed issue. When i try deploying using npm run build:dev. somehow it gets stuck on 

src\admin\client\routes\settings.js -> dist\admin\client\routes\settings.js

Any suggestion for that?

**Comment by diggschauhan** [comment]
Sorry figured this out, it was because of the --watch parameter added, it was not proceeding. removing that from package.config made it work :)

    "compile:dev": "babel src/admin -d dist/admin --watch & babel src/store -d dist/store --watch & babel theme/src -d theme/dist --watch", 

to

    "compile:dev": "babel src/admin -d dist/admin & babel src/store -d dist/store & babel theme/src -d theme/dist",

**Comment by restmount** [comment]
@diggschauhan nice.
