### ISSUE TITLE
Problem with checkout process

### ISSUE THREAD

**Issue by ceracera** [cezerin/cezerin#345]
Whenever I try to go to next checkout step after entering email on customer details checkout, form disappears and cart gets emptied.

That happens also when clicking on some fields on customer details form. Like when country field loses focus.

**Comment by ceracera** [comment]
Seems like order_id cookie is not being saved when on localhost. Maybe because it doesn't have domain value...

**Comment by restmount** [comment]
Hi @ceracera 
the problem in different domain and port for cookie on local environment.
If you use Nginx to proxy all from single domain - all work fine.
I will do a fix.

**Comment by ceracera** [comment]
Thanks. How could I do that? Do I have to use docker for that since I was trying to get it all up and running with just npm install and build?

**Comment by restmount** [comment]
In couple days will release a new version and new Docker image.

**Comment by ceracera** [comment]
Great. Your work, it looks great so far ;) What would you change in a new image?

**Comment by restmount** [comment]
Thanks.
New Docker image will include new release of Cezerin and updated Nginx config.

**Comment by restmount** [comment]
Hi @ceracera !
Fixed cookies with CORS.

**Comment by ceracera** [comment]
Great, thanks.
