### ISSUE TITLE
Can not add Product

### ISSUE THREAD

**Issue by sepicis** [cezerin/cezerin#347]
Hello, i was install cezerin in my server with CentOS 7 64 bit. I follow the installation guide and success installing cezerin and its default database. but, i can not add new product, the link not appear on right top (+) button. I try to edit that button link but still not show. I try to open diret link /admin/product/add but the desc of product not showing. How to fix this. thanks

**Comment by sepicis** [comment]
Solved! Thanks...

**Comment by sepicis** [comment]
Solved to create link, but can not save product to database. same with product categories, link add not show and can not find direct link to add product category.

**Comment by restmount** [comment]
@sepicis 
please, get a new version.
