### ISSUE TITLE
Log to console that unzip is needed for theme install

### ISSUE THREAD

**Issue by ceracera** [cezerin/cezerin#353]
theme-install.sh needs unzip on server and if there is no unzip, theme cannot be installed but there is no way to know why. Maybe log message to console, like echo 'You need unzip'... or add extract-zip with npm and use that.

**Comment by restmount** [comment]
Yeap, I use [docker image](https://github.com/cezerin/docker-cezerin/blob/master/images/0.31.0/Dockerfile) with all requirements

**Comment by restmount** [comment]
It's good idea to add this log message.

**Comment by restmount** [comment]
In future I think we'll replace **zip** and **unzip** with native Node modules.
