### ISSUE TITLE
How to handle tinymce content with react

### ISSUE THREAD

**Issue by ceracera** [cezerin/cezerin#354]
Suppose we have some user content that is linking, for example, a product in a web shop. Now a click on thet link will make the whole js app downloaded again. It would be great if react could handle that as well. Can that be done?

**Comment by restmount** [comment]
@ceracera 
I spent couple of days and can't solve it.

**Comment by restmount** [comment]
The idea was to replace links in HTML with React Router NavLink.
For now it's not a priority issue for me.
