### ISSUE TITLE
Facebook Customer Chat don't work after added Page ID

### ISSUE THREAD

**Issue by roboto-cloud** [cezerin/cezerin#356]
Hi, someone know how config it?

**Comment by sonufrienko** [comment]
@roboto-cloud
First, you need to setup Facebook SDK with Facebook App ID.

Then setup chat:
1. add your domain to whitelist ![](https://d33v4339jhl8k0.cloudfront.net/docs/assets/5570a2dce4b01a224b428f67/images/5a62fe5f2c7d3a39e6263152/file-gYRGPdJpEE.png)
2. get Page ID ![](https://d33v4339jhl8k0.cloudfront.net/docs/assets/5570a2dce4b01a224b428f67/images/5a61d9a20428632faf61f7bc/file-Nch6uUctfN.png)
3. set options on Dashboard ![](https://d33v4339jhl8k0.cloudfront.net/docs/assets/5570a2dce4b01a224b428f67/images/5a61d9b02c7d3a39e6262988/file-JUMDwlXAdB.png)

**Comment by sonufrienko** [comment]
I work in SaaS company and we offer Cezerin to our customers.
We host Cezerin as Docker containers in AWS.
