### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mgolkardev** [cezerin/cezerin#375]
Hi,
When i run `npm run build` in cmd, show this error:

![cezerin](https://user-images.githubusercontent.com/4500080/36265052-97d9e042-1283-11e8-8ca6-324322f69dc5.png)

Please help me.
Thanks a lot.

**Comment by restmount** [comment]
Hi @mgolkardev,
you should run `npm run build` at cezerin root directory.

**Comment by restmount** [comment]
Here `D:\rm\cezerin\`

**Comment by mgolkardev** [comment]
Hi **@restmount** 
Thanks for your support.
I run `npm run build` in `D:\rn\cezerin\`
![cezerin](https://user-images.githubusercontent.com/4500080/36267304-cf231dac-1288-11e8-92b9-cf6e4b060efd.png)

**Comment by restmount** [comment]
pls, show me content of 
1. root cezerin/ directory
2. and cezerin/config/ directory

**Comment by restmount** [comment]
I've never tested on Windows, so it's can be related to OS.
Have you a server/VM with Linux?

**Comment by mgolkardev** [comment]
Directories:

cezerin:
![cezerin](https://user-images.githubusercontent.com/4500080/36268138-05cdd5fc-128b-11e8-9be7-5580448f0896.png)

cezerin/config:
![cezerin_config](https://user-images.githubusercontent.com/4500080/36268153-0fd5be20-128b-11e8-96d8-12c1f2e92d19.png)

**Comment by mgolkardev** [comment]
```
I've never tested on Windows, so it's can be related to OS.
Have you a server/VM with Linux?
```

Not now but i test and say the result

**Comment by restmount** [comment]
Directory structure is right.
Why you have a yarn.lock?
How you install Cezerin?

**Comment by mgolkardev** [comment]
It is interesting to know:

If in `D:\rn\cezerin\node_modules\theme\dist\lib` change `var _store = require('../../../config/store');` to `var _store = require('../../../../config/store');` error fixed! (change 3 to 4 `../`)

and use from `D:\rn\cezerin\node_modules\theme` not `D:\rn\cezerin\node_modules\theme`!

Have an idea?

**Comment by mgolkardev** [comment]
`Directory structure is right.
Why you have a yarn.lock?
How you install Cezerin?`

```
cd D:\rn\
git clone https://github.com/cezerin/cezerin.git cezerin
cd cezerin
yarn (of course use npm i or npm install)
npm run build
npm run build:dev
```

**Comment by restmount** [comment]
I have a fresh clone and build - work fine on Linux.
I do:
1. git clone https://github.com/cezerin/cezerin
2. cd cezerin
3. npm i
4. npm run build

pls, try again.

**Comment by restmount** [comment]
Problem in Win or here `yarn (of course use npm i or npm install)`

**Comment by mgolkardev** [comment]
Thanks @restmount 
I test with `npm i` if not use linux

**Comment by shsunmoonlee** [comment]
This problem persists even when using npm
