### ISSUE TITLE
Replace SSE with WebSocket.

### ISSUE THREAD

**Issue by restmount** [cezerin/cezerin#377]
We need to replace Server-side Events with WebSocket.
The dashboard should receive events from WebSocket about new orders, payments, theme installation etc.

**Comment by restmount** [comment]
@sonufrienko can you help?

**Comment by restmount** [comment]
@centronius and @unitorio 
guys, con on, help needed.

**Comment by sonufrienko** [comment]
@restmount 
I have experience with WebSocket. I can do it.

**Comment by restmount** [comment]
Thanks, man.

**Comment by sonufrienko** [comment]
@restmount 
task completed and I like how it works :yum:

**Comment by restmount** [comment]
Yeah, WebSockets are really amazing and easy to use.
