### ISSUE TITLE
Not able to login to admin demo store

### ISSUE THREAD

**Issue by diggschauhan** [cezerin/cezerin#378]
![image](https://user-images.githubusercontent.com/35615777/36355340-8b2c9972-14d9-11e8-8802-c5fa1b147de0.png)

**Comment by restmount** [comment]
@diggschauhan 
I closed public access to the dashboard.
You can run your own dashboard.

**Comment by jay-aplan** [comment]
ok thanks. i tried running locally but i am getting errors while adding products. 

TinyMCE.js?9f39:114 Uncaught ReferenceError: tinymce is not defined
    at TinyMCE._init (TinyMCE.js?9f39:114)
    at TinyMCE.componentDidMount (TinyMCE.js?9f39:42)
    at commitLifeCycles (react-dom.development.js?cada:8770)
    at commitAllLifeCycles (react-dom.development.js?cada:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
    at commitRoot (react-dom.development.js?cada:10050)
    at performWorkOnRoot (react-dom.development.js?cada:11017)
    at performWork (react-dom.development.js?cada:10967)

I guess i am missing something. Will have a deeper look into it.

**Comment by restmount** [comment]
@diggschauhan 
in dev tools, check is every JS files loaded.

**Comment by restmount** [comment]
TinyMCE loaded with this
`<script src="/admin-assets/tinymce/tinymce-4.7.5.min.js" defer></script>`

**Comment by jay-aplan** [comment]
yes was just checking that. somehow tinymce.js is missing from public/admin-assets/tinymce. also countries.js is also missing from public/admin-assets/data. Not sure where they should be coming from.

**Comment by restmount** [comment]
@jay-aplan 
try to re-clone cezerin.
All admin assets located here: https://github.com/cezerin/cezerin/tree/master/public/admin-assets

**Comment by jay-aplan** [comment]
Thanks i think that resolved it. One unrelated question. Do you think this project is in the state I can use this to actually go live with a small e-commerce website? I mean would you think this is production ready?

**Comment by restmount** [comment]
@jay-aplan 
I launched couple small stores with a custom design - works very well. You can ask @sonufrienko , he offers hosted Cezerin.

**Comment by diggschauhan** [comment]
@restmount  thanks. Is there a deployment guide which can help for self hosting?

**Comment by restmount** [comment]
@diggschauhan 
There is no deployment guide for now. I will add it in a week.
Can you wait?

**Comment by diggschauhan** [comment]
@restmount  Thanks a bunch. I have been trying this for almost a week need to get something live soon. If you have anything even now that could help at all would be much appreciated :) Otherwise I will wait.

**Comment by diggschauhan** [comment]
@restmount  also a quick question. why api and store are running separately? is there a reason for that apart from following good design pattern of SOA?

**Comment by restmount** [comment]
Separate API and Store server allow you to scale with easy.
When you install theme with API we need to restart Store server.

**Comment by restmount** [comment]
Also it's better for security, performance and testing.

**Comment by diggschauhan** [comment]
@restmount thanks and i agree with all your points. On security point, what makes it more secure apart from enabling ORS only for one domain? Just for my understanding :)

**Comment by restmount** [comment]
API (public) should be available cross domain.
While AJAX api should be accessible only from your domain.

**Comment by diggschauhan** [comment]
@restmount thanks buddy :) any news on the deployment guide?

**Comment by restmount** [comment]
@diggschauhan 
[How to deploy a Cezerin on Ubuntu 16.04](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-16-04.md)

**Comment by restmount** [comment]
Also check updated docs.
