### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ranavc32** [cezerin/cezerin#382]
Hi I am trying to get this project started on Windows machine, but wasn't able to do so.
API is running, Connecting to DB is also done but its not able to start the store. Is there some changes need to be done in package.json file in order to make it run on windows machine.

Starting the store, externally using `npm run start-store` is not working same as example you have shown.
Is there any data need to be pushed initially in the database ?
Please help 

Thanks :)

**Comment by restmount** [comment]
Hi @ranavc32 
In a couple days I'll try to run Cezerin on Windows.
Pls, show your logs and errors.

**Comment by ranavc32** [comment]
@restmount , It didn't generate any errors initially and I was able to run the application but don't know whether I have to put some data in DB initially or I need to setup something else to make to same as **example of cezerin**  on windows as this example is running on docker I believe. 

Please let me know, when you run it on windows or have any thoughts or steps to run it on windows. :)

**Comment by ranavc32** [comment]
Hi @restmount ,

Hope you're doing well. Just wanted to check if you get any time to make it run on windows ?

**Comment by ranavc32** [comment]
I am closing it as I am able to run the project on Windows machine.
