### ISSUE TITLE
can't set orderes to paid and delivered status

### ISSUE THREAD

**Issue by ashmitaggarwal** [cezerin/cezerin#383]

**Comment by restmount** [comment]
Hi @ashmitaggarwal 
`paid` and `delivered` is a statuses for integrations.
Payment system will update your Order and set `paid` to `true`.
Integrations with shipping services will do the same.

**Comment by restmount** [comment]
You can add custom order statuses if you need.

**Comment by rorschach217** [comment]
understood.

**Comment by rorschach217** [comment]
@restmount one more question other then this thing, from customer side how can one see old orders ?? and in which status order is/are ??

**Comment by restmount** [comment]
@rorschach217 
Customers can't log in and check their orders, for now. This is on our roadmap. I plan to do passwordless login for customers.
