### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by prostoVladislav** [cezerin/cezerin#385]
system 4.9.83-1-MANJARO arch linux
node v9.6.1
mongodb v3.6.2

some magic
https://vimeo.com/257384183

**Comment by restmount** [comment]
Hi @prostoVladislav 
you need to restart store after each build.
Theme is locale package and cached by NodeJS.

So simple flow:
1. `npm run build` or `npm run build:dev`
2. `npm start` - each time on modification

My way - use pm2 with watch.

**Comment by prostoVladislav** [comment]
[okey ( ](http://fotohomka.ru/images/Nov/09/0ef93ded8f93970986bf6079dfa11c3f/mini_5.jpg)
Thank you!)

**Comment by restmount** [comment]
Soon, I'll publish better guides.

**Comment by francescotaioli** [comment]
@prostoVladislav i have problem with hot reload, can you help me please?

**Comment by SnijkoVladislav** [comment]
@francesco-taioli  I'm sorry, but I'm not working with this project anymore ¯\_(ツ)_/¯

**Comment by jjgumucio** [comment]
> Hi @prostoVladislav
> you need to restart store after each build.
> Theme is locale package and cached by NodeJS.
> 
> So simple flow:
> 
> 1. `npm run build` or `npm run build:dev`
> 2. `npm start` - each time on modification
> 
> My way - use pm2 with watch.

Could you elaborate a bit more on this?
Thanks in advance!

**Comment by SnijkoVladislav** [comment]
@jjgumucio I apologize but I do not remember all the magic (

**Comment by jjgumucio** [comment]
Now you can run:

1. npm run build:watch
2. pm2 start process.json

Then monitor the logs:

1. pm2 logs api
2. pm2 logs store
