### ISSUE TITLE
How to run on different port?

### ISSUE THREAD

**Issue by crobinson** [cezerin/cezerin#386]
Hi, i tryed with no problems on :3000 port, but what if i want to start it on 3002 or new port? changing it on config/server.js file run but not works on browser. Thanks

**Comment by restmount** [comment]
Hi @crobinson 
do you use Docker or Nginx?

**Comment by crobinson** [comment]
Apache

**Comment by restmount** [comment]
@crobinson 
pls, show more logs
1. browser response
2. config/server

In config/server.js you need to change:

1. `storeBaseUrl: "http://localhost:3000",` - Access-Control-Allow-Origin
2. `storeListenPort: 3000,` - Node server
