### ISSUE TITLE
Page not found error on initial setup

### ISSUE THREAD

**Issue by zachfagerness** [cezerin/cezerin#388]
I set up the project in the most regular way possible, and got Page not found The page you requested does not exist. Click here to continue shopping. 

In src/store/shared/app.js in the render function currentPage.type is set to 404 but if I manually set it to currentPage.type = PAGE then everything works reasonably fine. 

I also tried it in docker with the same outcome.

Thoughts anyone? Also I'd just like to say thank you for making this! I was doing the exact same thing when I found it saved me loads of time.

**Comment by restmount** [comment]
Hi @zachfagerness 
you need to add default data to MongoDB
```js
db.pages.insertMany([
  {slug: '', meta_title: 'Home', enabled: true, is_system: true},
  {slug: 'checkout', meta_title: 'Checkout', enabled: true, is_system: true},
  {slug: 'checkout-success', meta_title: 'Thank You!', enabled: true, is_system: true},
  {slug: 'cart', meta_title: 'Cart', enabled: true, is_system: true},
  {slug: 'login', meta_title: 'Login', enabled: true, is_system: true},
  {slug: 'logout', meta_title: 'Logout', enabled: true, is_system: true},
  {slug: 'register', meta_title: 'Register', enabled: true, is_system: true},
  {slug: 'account', meta_title: 'Account', enabled: true, is_system: true}
]);
```

**Comment by restmount** [comment]
try in terminal
1. `mongo shop`
2. paste this data

**Comment by nteej** [comment]
@restmount,its working perfectly.Thanks a lot.

**Comment by noenteas** [comment]
![image](https://user-images.githubusercontent.com/30532126/46912076-82870000-cf32-11e8-800c-310b643cfd23.png)

Login not found :/ 

![image](https://user-images.githubusercontent.com/30532126/46912079-9cc0de00-cf32-11e8-9a85-ed9d9584cd46.png)

Help me !!
