### ISSUE TITLE
Error on login page on production

### ISSUE THREAD

**Issue by jay-aplan** [cezerin/cezerin#389]
Hi
I tried deploying it on hosting server. Getting couples of errors on it. I am running the store and api using pm2 (process.json on ports 3000 and 3001)

apiClient.js?ad89:97 OPTIONS http://uniquecloud9tu6.cloud:3001/api/v1/authorize net::ERR_CONNECTION_TIMED_OUT

apiWebSocket.js?2c62:22 WebSocket connection to 'ws://uniquecloud9tu6:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

Uncaught (in promise) Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development

Any clue?

**Comment by restmount** [comment]
@jay-aplan 
Please check this guide
[How to deploy a Cezerin on Ubuntu 16.04](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-16-04.md)
