### ISSUE TITLE
Your docker pm2 setup

### ISSUE THREAD

**Issue by zachfagerness** [cezerin/cezerin#391]
Any way I could get a even basic guide on how to do your current setup I've seen you describe with docker and pm2 for live reload? It's the one thing holding me back from really developing the hell out of it, as I couldn't get a typical webpack-dev-server to work either

**Comment by restmount** [comment]
@zachfagerness 
check updated guide with pm2
https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

**Comment by restmount** [comment]
I spent a day to run Cezerin with webpack-dev-server and hot reload. Cezerin uses server-side rendering, so it's cant help. You still need to refresh a browser page.

**Comment by zachfagerness** [comment]
awesome thanks man
