### ISSUE TITLE
Suggest " One Page Checkout"feature.

### ISSUE THREAD

**Issue by channingbox** [cezerin/cezerin#394]
Suggest  "One Page Checkout" feature.
Two mode: 
1.Full step by step checkout
2.One Page checkout (remove "customer details, simplified address")，"name,address,phone" must be, "comments" optional.

![onepage](https://user-images.githubusercontent.com/14830934/37198739-4398bd1c-23ba-11e8-9b1d-c95bd57b33b2.png)

**Comment by restmount** [comment]
@channingbox 
checkout process differs from country to country. Especially in Europe.
I plan in future add second checkout module.

**Comment by restmount** [comment]
@channingbox 
checkout process differs from country to country. Especially in Europe.
I plan in future add second checkout module.
