### ISSUE TITLE
npm start failed 

### ISSUE THREAD

**Issue by kaiomi** [cezerin/cezerin#396]
npm start failed in ubuntu

npm start

module.js:328
    throw err;
    ^

    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-store"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 start-store: `node dist/store/server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 start-store script 'node dist/store/server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/store/server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gise/Desktop/workspace/trascimage/npm-debug.log

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 start: `NODE_ENV=production npm run start-api & npm run start-store`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 start script 'NODE_ENV=production npm run start-api & npm run start-store'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production npm run start-api & npm run start-store
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-api"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 start-api: `node src/api/server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 start-api script 'node src/api/server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/api/server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    /npm-debug.log

This is the npm-debug.log
>>>>>>>>>>>>>>>>>
17 error Linux 4.4.0-112-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-api"
19 error node v4.2.6

**Comment by restmount** [comment]
@kaiomi 
please pull and try new version.
Also, check new guide https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

**Comment by sonufrienko** [comment]
@kaiomi 
You need Node.js v8.10 LTS.
