### ISSUE TITLE
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin'

### ISSUE THREAD

**Issue by annguyen36** [cezerin/cezerin#397]
I tried to run "npm run build"
Then appear this error. and I have issue with npm start. 
"annguyen36:~/workspace/cezerin (master) $ npm run build

> cezerin@0.33.0 build /home/ubuntu/workspace/cezerin
> NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin

> cezerin@0.33.0 compile /home/ubuntu/workspace/cezerin
> babel src/store -d dist/store --quiet

> cezerin@0.33.0 theme:build /home/ubuntu/workspace/cezerin
> babel theme/src -d theme/dist --quiet && npm run webpack:store

> cezerin@0.33.0 webpack:store /home/ubuntu/workspace/cezerin
> webpack --config webpack.config.store.js --mode production

Hash: b2af1e2f0e2ef9072973
Version: webpack 4.1.1
Time: 32163ms
Built at: 3/12/2018 12:55:07 AM
 2 assets
Entrypoint app = assets/js/app-e441451a78a502bb9f2e.js
Entrypoint theme = assets/js/theme-9eb3390c7dd2fb28e1da.js
   [9] ./node_modules/react-redux/es/index.js + 14 modules 37.4 KiB {1} [built]
       |    15 modules
  [14] ./node_modules/redux/es/index.js + 6 modules 20.6 KiB {1} [built]
       |    7 modules
  [66] ./node_modules/redux-form/es/index.js + 225 modules 296 KiB {1} [built]
       |    226 modules
  [67] ./src/store/shared/actions.js 19.3 KiB {1} [built]
  [74] (webpack)/buildin/global.js 509 bytes {1} [built]
 [140] ./node_modules/react-router-dom/es/index.js + 13 modules 13.4 KiB {1} [built]
       |    14 modules
 [147] ./src/store/shared/analytics/index.js 3.74 KiB {1} [built]
 [148] ./src/store/shared/actionTypes.js 2.76 KiB {1} [built]
 [194] multi theme 28 bytes {0} [built]
 [195] ./src/store/shared/containers/search.js 596 bytes {1} [built]
 [196] ./src/store/shared/containers/notfound.js 598 bytes {1} [built]
 [277] ./src/store/shared/app.js 5.83 KiB {1} [built]
 [279] ./src/store/shared/reducers.js 3.88 KiB {1} [built]
 [295] ./src/store/client/index.js 1.52 KiB {1} [built]
 [498] multi babel-polyfill ./src/store/client/index.js 40 bytes {1} [built]
    + 486 hidden modules

ERROR in multi theme
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin'
 @ multi theme

ERROR in ./src/store/shared/containers/shared.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/shared.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/index.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/index.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/category.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/category.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/product.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/product.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/page.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/page.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/checkoutSuccess.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/checkoutSuccess.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/notfound.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/notfound.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/search.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/search.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/checkout.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/workspace/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/checkout.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js
Child html-webpack-plugin for "assets/index.html":
     1 asset
    Entrypoint undefined = assets/index.html
       [0] (webpack)/buildin/module.js 519 bytes {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] ./node_modules/html-webpack-plugin/lib/loader.js!./theme/index.html 2.49 KiB {0} [built]
        + 1 hidden module

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "run" "webpack:store"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 webpack:store: `webpack --config webpack.config.store.js --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 webpack:store script 'webpack --config webpack.config.store.js --mode production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.config.store.js --mode production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/cezerin/npm-debug.log

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "run" "theme:build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 theme:build: `babel theme/src -d theme/dist --quiet && npm run webpack:store`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 theme:build script 'babel theme/src -d theme/dist --quiet && npm run webpack:store'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel theme/src -d theme/dist --quiet && npm run webpack:store
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/cezerin/npm-debug.log

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cezerin@0.33.0 build: `NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 build script 'NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cezerin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cezerin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cezerin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/cezerin/npm-debug.log"

Please help me.
Thanks a lot.

**Comment by ceracera** [comment]
I think you should have newer version of node. Try instaling with node 8.9

**Comment by restmount** [comment]
I use LTS Node 8.10.

**Comment by ludapops** [comment]
thanks Ill give it a shot

**Comment by Tarvald** [comment]
Anyone resolved this issue? 
It is happened to me on two environments 
Linux and mac.
I tried different node versions changing them by nvm.

**Comment by restmount** [comment]
What's your Node.js and NPM version?
Do you execute `npm run build` in root folder?

**Comment by tidusvn05** [comment]
i just got same problem.

My env:
node v8.11.1
npm 5.6.0
cezerin lastest

**Comment by restmount** [comment]
Just to clarify you do this:
1. `npm i`
2. `npm run build`
3. `npm start`

Check you console log.
Does **dist** folder exists on root and on /theme folder?

**Comment by ampsarfraz** [comment]
I am also facing the same issue on windows. have the latest version of the code , Node version is 8.11.2 . Can you please let me know how to resolve this?

**Comment by amp9020** [comment]
sorry to distract you @restmount , i too got the same message in this ticket.  running latest everything & fresh build. I was following your instructions for "Getting started with github"

**Comment by amp9020** [comment]
Actually, I got it to work.  Unconfirmed:   it was webpack as the issue.

**Comment by dukemai** [comment]
Now I got the same issue on Mac. I am running npm 6.3.0. any ideas?

**Comment by sonufrienko** [comment]
@dukemai 
```
npm i && npm run build && npm start
```
if you'll see errors, please attach it here.

**Comment by dukemai** [comment]
thanks, it works now. what is the difference between my previous steps. I did
1) yarn
2) yarn run build => failed here

**Comment by owserge** [comment]
I have the same issue on Mac OS.
node -v > v8.11.4
npm -v > 5.10.0
sw_vers >
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

**Comment by HaswinVidanage** [comment]
+1 same issue

**Comment by dewelloper** [comment]
npm i --f

**Comment by elissaioskon** [comment]
same issue, that happens when i use yarn. Finally with `npm i && npm run build && npm start` it works.

**Comment by dewelloper** [comment]
it couldnt seen theme folder while working shallow version of nmp, you can install packet if your npm is stable with the pocket version "npm i --f" otherwise you should upgare to high version of the npm with this command "npm i npm-upgrade" And this is the joined command to building and running the project "npm i && npm run build && npm start" Also if your npm pocket less then project this command wont work with a reason that old npm version doesnt recognise the && command joining. Share for all..

**Comment by darshan0071990** [comment]
+1

**Comment by fkonovalov** [comment]
I had the same problem on the 8.10 node version. Was solved by installing version 8.12

**Comment by bicendinh** [comment]
my solution: Run npm i --save ./theme -> npm run build
