### ISSUE TITLE
Can't install in Windows

### ISSUE THREAD

**Issue by soontorn** [cezerin/cezerin#400]
I followed installation instruction in
https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md

git clone https://github.com/cezerin/cezerin.git cezerin
cd cezerin
npm install
npm run build

I ran into a few issues.
The first issue is that the command
NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin

'NODE_ENV' is not recognized as an internal or external command,

I fixed by changing the file package.json in the line build to
set NODE_ENV=production npm run compile && npm run theme:build && npm run webpack:admin
Then I ran into another issue the log is attached:
[log.txt](https://github.com/cezerin/cezerin/files/1810137/log.txt)

Any suggestion on how to fix this?

**Comment by sonufrienko** [comment]
@soontorn 
I also see this warning. I think you can skip them for now. Until Webpack plugins updated.

**Comment by soontorn** [comment]
Hmm npm start produces errors though:

> cezerin@0.33.0 start C:\Users\soontorn\Downloads\cezerin
> set NODE_ENV=production npm run start-api & npm run start-store


> cezerin@0.33.0 start-store C:\Users\soontorn\Downloads\cezerin
> node dist/store/server/index.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Users\soontorn\Downloads\cezerin\dist\store\server\index.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin@0.33.0 start-store: `node dist/store/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin@0.33.0 start-store script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\soontorn\AppData\Roaming\npm-cache\_logs\2018-03-14T10_37_13_338Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin@0.33.0 start: `set NODE_ENV=production npm run start-api & npm run start-store`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin@0.33.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\soontorn\AppData\Roaming\npm-cache\_logs\2018-03-14T10_37_13_355Z-debug.log

**Comment by soontorn** [comment]
The dist folder does not exist....

**Comment by sonufrienko** [comment]
dist folder can be not exist only if you missed `npm run build`

**Comment by soontorn** [comment]
hmm I ran npm run build already (as in the log attached in the above post) but dist was not created. Any idea?

**Comment by sonufrienko** [comment]
try `npm run compile` - this will compile code and create dist folder

**Comment by soontorn** [comment]
Thanks! That works. 
Now when go to 
http://localhost:3000/

with Chrome, I got
{"name":"FetchError","message":"request to http://localhost:3001/api/v1/settings? failed, reason: connect ECONNREFUSED 127.0.0.1:3001","type":"system","errno":"ECONNREFUSED","code":"ECONNREFUSED"}

in the command prompt, I got
error: Page error / FetchError: request to http://localhost:3001/api/v1/settings? failed, reason: connect ECONNREFUSED 127.0.0.1:3001
    at ClientRequest.<anonymous> (C:\Users\soontorn\Downloads\cezerin\node_modules\isomorphic-fetch\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by soontorn** [comment]
http://localhost:3000/admin
shows the Dashboard though

**Comment by soontorn** [comment]
BTW, I already installed mongodb and followed the steps 
https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md
without any error

**Comment by soontorn** [comment]
OK found the issue:
When I run 
npm start

> cezerin@0.33.0 start C:\Users\soontorn\Downloads\cezerin
> set NODE_ENV=production npm run start-api & npm run start-store


> cezerin@0.33.0 start-store C:\Users\soontorn\Downloads\cezerin
> node dist/store/server/index.js

info: Store running at http://localhost:3000

**Comment by soontorn** [comment]
only the store runs, but not the api

I had to manually do
npm run start-api
in a prompt and
npm run start-store
in another prompt, then it works!

**Comment by soontorn** [comment]
I got 
![image](https://user-images.githubusercontent.com/11569000/37400138-81be5912-27b6-11e8-91e9-d3e4dfee33bd.png)

is this right?

**Comment by sonufrienko** [comment]
Oh, you almost did it on Windows. You are a superhero! :+1: 
1. you need to add pages to MongoDB - this will fix **Page not found**
2. set your domain in dashboard, page - Settings, set http://localhost:3000 - this will fix images

**Comment by soontorn** [comment]
Hmmm how do I do 1?
I followed https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md already, but it doesn't help

For 2, did it already, but images still do not show...

**Comment by sonufrienko** [comment]
@soontorn 
1. Check twice - if you see **page not found** you don't add pages to DB. Check database with name **shop**
2. show me your image URL

**Comment by soontorn** [comment]
1. This is the DB
![image](https://user-images.githubusercontent.com/11569000/37415572-5337bc8c-27de-11e8-892f-482a5f848901.png)

there's nothing in shop, but there are a lot of info in test

2. What image are you referring to?

Thanks!

**Comment by soontorn** [comment]
ok after I delete test and shop then run
mongo shop 
and followed the rest of instructions from 
https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md
again, I now have
![image](https://user-images.githubusercontent.com/11569000/37415943-3a079984-27df-11e8-9181-c3a80233bf27.png)

**Comment by soontorn** [comment]
for 2, do you mean this?
<img src="http://localhost:3000/images/products/5aa94d84534b1a4910a6a501/340/20180216_215830.jpg" alt="sss" title="sss">

I added a category and a product and got this:
![image](https://user-images.githubusercontent.com/11569000/37416531-93a2aeb0-27e0-11e8-9c55-66fd1a500f17.png)

The img element above is from the broken image link of the product sss

**Comment by soontorn** [comment]
I added an image for the product already. Nothing happens when clicking on the product though

**Comment by sonufrienko** [comment]
1. check domain on Settings http://localhost:3000/admin/settings
2. open browser console and check errors

**Comment by soontorn** [comment]
This is the settings:
![image](https://user-images.githubusercontent.com/11569000/37439927-f899b808-282c-11e8-836e-c57c2c9660e2.png)

This is the browser console when I open localhost:3000

![image](https://user-images.githubusercontent.com/11569000/37439957-1eb863f4-282d-11e8-8f29-5a2c72328644.png)

**Comment by soontorn** [comment]
Any help, please...

**Comment by soontorn** [comment]
Oh I have a category with slug "ddd" and a product with slug "what".
The error shows up because I clicked on the product

**Comment by soontorn** [comment]
![image](https://user-images.githubusercontent.com/11569000/37523810-a44eb42c-295a-11e8-8733-a6febf5aaac6.png)
if I refresh, I got this. The image seems to be not found

**Comment by soontorn** [comment]
Hmm ok after I upload the image again, it shows up but when I click on it, I got the same pushState error

**Comment by soontorn** [comment]
![image](https://user-images.githubusercontent.com/11569000/37524049-4dd5f622-295b-11e8-8a80-54014e4a311a.png)
Ok now I rename category slug to test1_slug and product slug to prod_slug.
This is the error after I click on the product (heart image)

**Comment by sonufrienko** [comment]
Seems like your domain not set.
Refresh settings page or check in database.
Your product URL must be
`http://<domain-from-settings>/<category-slug>/<product-slug>`
but it:
`http://<empty>/<category-slug>/<product-slug>`

**Comment by soontorn** [comment]
Hmm it seems to be set correctly:
![image](https://user-images.githubusercontent.com/11569000/37526413-d99dbe14-2961-11e8-9481-518245166433.png)

What strange is that if I hover over the heart image, correct URL shows on the bottom left of my browser
![image](https://user-images.githubusercontent.com/11569000/37526475-0aa1aed0-2962-11e8-9d75-80c4b0e1f5dd.png)

If I visit that URL manually, I can add product to cart and check out!

**Comment by sonufrienko** [comment]
This can be a cache.
Also check open this product on the category page, not from home page.

**Comment by soontorn** [comment]
Hmm cleared the cache, still got same error. 
Tried open the product on the category page, still got same problem. (In Chrome)

Tried using Edge, it navigates to 
http://localhost:3000//test1_slug/prod1_slug
which results in page not found.

Tried deleting cezerin from my computer, delete DB, and redo all the installation from scratch, still got the exact same problem...

**Comment by sonufrienko** [comment]
@soontorn 
what is your slug for category and product?
It's must be clear text without a sash.

**Comment by ranavc32** [comment]
Finally, I am on the same page, Thanks for the discussion and help @sonufrienko . Now We are stuck at clicking on an item, it's throwing an error as pointed out by @soontorn . Any fixes why this is happening. 

Thank you for this amazing project :)

**Comment by sonufrienko** [comment]
Just fixed. Now you can run on Windows.

**Comment by restmount** [comment]
@sonufrienko 
Thanks for your help.

**Comment by soontorn** [comment]
@sonufrienko 
Thanks a lot, just tested and it works now!
