### ISSUE TITLE
Help installing Cezerin on Heroku

### ISSUE THREAD

**Issue by tennysonp** [cezerin/cezerin#404]
I was able to run the application on my local machine but wanted to push it to heroku but it isn't working at all. 

Does anyone know how to install Cezerin on Heroku???

Thanks Much

**Comment by tennysonp** [comment]
Wow thanks for your help, I’ll let try it. Does the file upload work on Heroku?

**Comment by tennysonp** [comment]
The product images

**Comment by sivarajng** [comment]
This is another issue am facing , If I upload a product image on the heroku app the file is not being uploaded/created under path \public\content\images\products\*

However if I already uploaded the images in my localhost app and then deployed the code base to heroku, then the images are loaded.

**Comment by sivarajng** [comment]
Hi, Thanks, I checked with Heroku documentation https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem, and it seems like generally file not persists in a heroku instance, so I probably need to rely on some cloud storage or store the uploaded image(base64) on the mongoDB itself.

**Comment by tigrankhachikyan** [comment]
May be it makes sense to give Cloudinary url as a product image?

**Comment by dr-montasir** [comment]
>     1. app.json file as per Heroku doc.



> 
> 
> Hi, due to cezerin's architecture I could not able to find a way to host in same instance, so I hosted the app in 2 separate Heroku instances. If you already able to run cezerin in localhost then there's nothing much todo to run the same on Heroku except below few steps:
> 
> e.g.
> 
>     1. created 2 instances like
> 
> 
>     * http://app.herokuapp.com for api
> 
>     * http://app-client.herokuapp.com for store
> 
> 
>     1. add app.json file as per Heroku doc.
> 
>     2. find and replace all
> 
> 
>     * localhost:3000 to app-client.herokuapp.com for store
> 
>     * localhost:3001 to app.herokuapp.com for api
> 
> 
>     1. modify config/server.js as like below:
> 
> 
>     * apiListenPort: process.env.PORT || 3001,
> 
>     * storeListenPort: process.env.PORT || 3000,
> 
> 
>     1. deploy the same cezerin code base to both the instances with below respective start/main script in package.json
> 
> 
>     * "start": "node dist/store/server/index.js", for store's instance
> 
>     * "start": "node src/api/server/index.js", for api's instance
> 
> 
>     1. make sure dist/ and theme/* theme/dist/* are also uploaded properly (i.e.) .gitignore to ignore only node_modules dir
> 
> 
> Hope this answer helps


Thanks

Please provide the example code for both API and client

**Comment by dr-montasir** [comment]
Thank you everything is going well
