### ISSUE TITLE
start-api fails - Exit status 1

### ISSUE THREAD

**Issue by kerven66** [cezerin/cezerin#408]
Happens when running "npm start" for the first time. I know there's a closed issue similar to this one, but upgrading node is not solution for me, because I'm working with 9.8.0 version.

This is the content of debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cezerin@0.33.0prestart: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0start: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0start: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/vhosts/ees.es/httpdocs/cezerin/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
9 verbose lifecycle cezerin@0.33.0start: CWD: /var/www/vhosts/ees.es/httpdocs/cezerin
10 silly lifecycle cezerin@0.33.0start: Args: [ '-c',
10 silly lifecycle 'NODE_ENV=production npm run start-api & npm run start-store' ]
11 silly lifecycle cezerin@0.33.0start: Returned: code: 1 signal: null
12 info lifecycle cezerin@0.33.0start: Failed to exec start script
13 verbose stack Error: cezerin@0.33.0 start: NODE_ENV=production npm run start-api & npm run start-store
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack at EventEmitter.emit (events.js:180:13)
13 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:180:13)
13 verbose stack at maybeClose (internal/child_process.js:936:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /var/www/vhosts/ees.es/httpdocs/cezerin
16 verbose Linux 3.10.0-693.17.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.8.0
19 verbose npm v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start: NODE_ENV=production npm run start-api & npm run start-store
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sonufrienko** [comment]
@kerven66 
Try to use Node.js v 8.10 LTS.

**Comment by kerven66** [comment]
Ok, I'll have to try tomorrow. I'm going to work now. Thankyou

**Comment by kerven66** [comment]
I've downgraded to v.8.10 LTS and restarted server, but when I try to start with pm2 I get this error:

Error: listen EADDRINUSE :::3001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/var/www/vhosts/elespejitoroto.es/httpdocs/cezerin/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/var/www/vhosts/elespejitoroto.es/httpdocs/cezerin/src/api/server/index.js:35:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by sonufrienko** [comment]
> listen EADDRINUSE :::3001
Port 3001 in use. Try to find and kill this Node process.

**Comment by kerven66** [comment]
There was nothing using port 3001. I've restarted server again and now, when I start process, it doesn't throw any error, but I can't change or add nothing in dashboard. The app read the default data of the db, but if you change or add something and clic "save button", nothing at all is saved.

**Comment by restmount** [comment]
@kerven66 
please, show your browser console with errors.

**Comment by kerven66** [comment]
Sorry, I should have sent before. This error is constantly repeated when you start process, even without doing anything:

app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1
app-3033d1434f0cf662daa1.js:1 WebSocket connection closed with code: 1006.
localhost:3001/api/v1/settings? Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:3001/api/v1/orders?cancelled=false&date_placed_min=2018-02-21T23%3A00%3A00.188Z&draft=false Failed to load resource: net::ERR_CONNECTION_REFUSED
app-3033d1434f0cf662daa1.js:1 TypeError: Failed to fetch
app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1
app-3033d1434f0cf662daa1.js:1 WebSocket connection closed with code: 1006.
app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1
app-3033d1434f0cf662daa1.js:1 WebSocket connection closed with code: 1006.
app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1
app-3033d1434f0cf662daa1.js:1 WebSocket connection closed with code: 1006.
app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1
app-3033d1434f0cf662daa1.js:1 WebSocket connection closed with code: 1006.
app-3033d1434f0cf662daa1.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
u @ app-3033d1434f0cf662daa1.js:1

**Comment by restmount** [comment]
@sonufrienko 
Please, check this error message.

`WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by kerven66** [comment]
You're right. I am new to this and I had not correctly interpreted the error.

Thankyou so much

**Comment by dewelloper** [comment]
hello all how do you debugging this app
