### ISSUE TITLE
Nested categories

### ISSUE THREAD

**Issue by sorokinvj** [cezerin/cezerin#410]
Hi, guys.

I would like to have nested categories, so I can arrange products in the shop  as 

→ Beverages 
→→ Water
→→→ Still
→→→ Sparkling
→→ Cola
→→→ Pepsi
→→→ Coca-Cola
→→ Juices
→→→ Orange
→→→ Apple 

Problem is that I am newbie in server-side and db coding, so I would really appreciate if someone could point me to that direction – where to start? How should I change the model? Just add parents-children in categories?

**Comment by sonufrienko** [comment]
@sorokinvj 
Nested categories are already implemented.
1. open category to edit
2. click on the folder icon in the header to move a category to another parent

You can build any tree you want.

**Comment by sorokinvj** [comment]
wow, first of all thanks!

secondly, you should definetely change the ux – it is sooooo unusual for this task!

**Comment by sorokinvj** [comment]
I'll try to come up with some changes and suggest them

**Comment by sonufrienko** [comment]
@restmount 
this is your UI :rofl:
