### ISSUE TITLE
Order checkout-success page redirect on online payment 

### ISSUE THREAD

**Issue by ashmitaggarwal** [cezerin/cezerin#411]
Hi 

I have added my local country payment gateway. How to redirect to checkout-suucess page once i get payment from the gateway.

Error Shows : Cannot POST /checkout-success

SuccessPayment-URL on gateway SDK is : /checkout-success.

Step:-> After clicking Pay Now. User is redirect to payment gateway page where payment is made .
Payment gateway asks for Success URL -> Success payment url and Failed gateway URL.

I am having issue which only success url that how to get order placed page  

Please help

**Comment by sonufrienko** [comment]
@ashmitaggarwal 
Do you solve your issue or still need help?

**Comment by ashmitaggarwal** [comment]
issue solved
