### ISSUE TITLE
Unexpected end of JSON input while parsing near '...um-stream":"^1.0.2","'

### ISSUE THREAD

**Issue by mkouchi** [cezerin/cezerin#412]
...
ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-helper-function-name-621030ed/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-helper-explode-assignable-expression-927e0786/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-helper-call-delegate-d8bdcff5/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-template-002033d9/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-helper-bindify-decorators-42dc7978/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-plugin-transform-es2015-function-name-c21b36a2/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/babel-helper-function-name-621030ed/README.md'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/uglify-es-f00cb3af/lib/minify.js'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/uglify-es-f00cb3af/lib/mozilla-ast.js'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/uglify-es-f00cb3af/lib/output.js'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/webpack-cli-17cde3b2/.nyc_output/835b0d393ceec036662e3529b0272122.json'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/source-map-2a249e9a/dist/source-map.js'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/webpack-cli-17cde3b2/.nyc_output/880833224714cb8858ccb77724979101.json'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/webpack-cli-17cde3b2/.nyc_output/8bbb03eaf65ca83c7e494a62d105f8fc.json'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/webpack-cli-17cde3b2/.nyc_output/8f27269b188e61a59bbf5827de818c30.json'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/webpack-cli-17cde3b2/.nyc_output/9241e51b5c2cccf5e78e2246c0243746.json'
npm WARN tar ENOENT: no such file or directory, open '.../cezerin/node_modules/.staging/unicode-575fabd0/category/Nd.js'
npm ERR! Unexpected end of JSON input while parsing near '...um-stream":"^1.0.2","'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mohammad/.npm/_logs/2018-03-25T05_47_26_069Z-debug.log

using node v8.10.0, npm  v5.6.0
I tried removing node_modules folder, but no success.

**Comment by sonufrienko** [comment]
@mkouchi 
Do you run `npm install` and `npm run build` in Cezerin folder?
From logs, I suppose, you run in parent or child folder.

**Comment by mkouchi** [comment]
Dear @sonufrienko 
Yes, I run in Cezerin folder, I think this is because of internet restrictions in our country, Iran, I'll try with proxy to check.
If you have any idea please help, thanks.

**Comment by sonufrienko** [comment]
@mkouchi 
1. did `node_modules` folder create? Is it contains files or folders?
2. did `dist` folder create? Is it contains files or folders?

Hmm, restricting access to **npmjs.com** sounds unbelievable.

**Comment by mkouchi** [comment]
@sonufrienko 
Restricting because of US sanctions, not internal filtering.
I fixed that by npm cache clean and runing again.
 
Thanks a lot.
