### ISSUE TITLE
Error when adding item to cart

### ISSUE THREAD

**Issue by GotHima** [cezerin/cezerin#413]
When I tried to add an item to the cart, I received an error in the Developer console:
POST http://localhost:3001/ajax/cart/items 500 (Internal Server Error)

Upon checking the pm2 error log file, I found this:
[31merror[39m: API error TypeError: Cannot read property 'length' of undefined
    at OrderItemsService.calculateAndUpdateItem (C:\Users\User\github\cezerin\src\api\server\services\orders\orderItems.js:186:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by restmount** [comment]
Seems like a bug.

**Comment by sonufrienko** [comment]
Fixed

**Comment by andrclp** [comment]
Hi!
I am getting same error.

<img width="561" alt="screenshot 2019-01-05 at 21 43 53" src="https://user-images.githubusercontent.com/13333811/50728483-20a1f500-1133-11e9-9411-6a6f8bb84340.png">
