### ISSUE TITLE
Help with https

### ISSUE THREAD

**Issue by ceracera** [cezerin/cezerin#416]
How would you serve webshop with https? I thought to:

1) generate certificates with something like LetsEncrypt's certbot,
2) add https module to /src/store/server/index.js and point https server options to key and cert files,
4) change config/{store/admin/server} to use https://<domain>

Would that work? Is that the way to do it?

**Comment by ceracera** [comment]
I managed to set it up that way. I had to set https in /src/api/server/index.js as well. Is there a better way, somehow already enabled in the app?

**Comment by sonufrienko** [comment]
1. CloudFlare service (setup and forget)
2. Let’s Encrypt (need to setup automatic auto renew)
3. AWS Certificate Manager

I use CloudFlare everywhere I can - free, secure and painless.
Otherwise I use Let’s Encrypt with Nginx.

**Comment by restmount** [comment]
@ceracera 
I suggest you to use Nginx with Let's Encrypt in front of Node.js.
