### ISSUE TITLE
NPM start Error

### ISSUE THREAD

**Issue by ghost** [cezerin/cezerin#418]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xxxx/.nvm/versions/node/v8.10.0/bin/node',
1 verbose cli   '/Users/xxxx/.nvm/versions/node/v8.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-api' ]
2 info using npm@5.8.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start-api: PATH: /Users/xxxx/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xxxx/Code/cezerin/node_modules/.bin:/Users/xxxx/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xxxx/Code/cezerin/node_modules/.bin:/Users/xxxx/.nvm/versions/node/v8.10.0/bin:/Users/xxxx/.rbenv/shims:/Users/xxxx/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
9 verbose lifecycle cezerin@0.33.0~start-api: CWD: /Users/xxxx/Code/cezerin
10 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
11 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
13 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/xxxx/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/xxxx/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /Users/xxxx/Code/cezerin
16 verbose Darwin 17.4.0
17 verbose argv "/Users/xxxx/.nvm/versions/node/v8.10.0/bin/node" "/Users/xxxx/.nvm/versions/node/v8.10.0/bin/npm" "run" "start-api"
18 verbose node v8.10.0
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start-api script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by oc-shady** [comment]
clear! it's because of used 'yarn build'

**Comment by restmount** [comment]
Please, describe more details: environment, you flow and commands.

**Comment by gddabe** [comment]
exactly the same issue, but with 
```
2 info using npm@5.8.0
3 info using node@v9.11.1
```

environment: `macOS v10.13.4`
flow+cmds: `git clone, cd cezerin, npm install, npm run build, npm start`
