### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by juhamm** [cezerin/cezerin#419]
I'm trying to setup environment in Centos 6.
Installation with GIT went well and shop is running, however when I try to add categories or products "+" button do nothing and if I try for example change currency or any other values, they do not store in the Mongo?

Any idea what is missing?

Monge version is: MongoDB shell version v3.6.3
Nodejs: v8.11.1

[root@React cezerin]# npm start
> cezerin@0.33.0 start /var/nodejs/cezerin
> npm run start-api & npm run start-store
> cezerin@0.33.0 start-api /var/nodejs/cezerin
> node src/api/server/index.js
> cezerin@0.33.0 start-store /var/nodejs/cezerin
> node dist/store/server/index.js
info: Store running at http://localhost:3000
info: API running at http://localhost:3001
info: MongoDB connected successfully

**Comment by juhamm** [comment]
Anyone can help? @restmount @sonufrienko ??

**Comment by w-site** [comment]
@juhamm Hi. Tru to initialize mongo data https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md

**Comment by juhamm** [comment]
https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md
this was already done...  :(

**Comment by juhamm** [comment]
is this some kind of permission Problem? I've even given 777 to /var/lib/mongo .. but still there is a same problem.

**Comment by restmount** [comment]
@juhamm 
1. check server logs in console
2. check logs `/logs/server.log`

Just to clarify: 
1. you can login to MongoDB and insert data manually
2. app can read data
3. app can't write data

Right?
Do you use MongoDB auth?

**Comment by juhamm** [comment]
Hi,

Got this solved :/ My bad!
Need to change /config/server.js, store.js, admin.js  localhost to ip-address
How stupid I was :) 

Juha
