### ISSUE TITLE
script to add default data when first setting up

### ISSUE THREAD

**Issue by mrhut10** [cezerin/cezerin#426]
Does anyone else thing it would be a good idea to have a script to inject default data,
which would help new users like me to get started?

is there a import data script already??

**Comment by restmount** [comment]
@mrhut10 
This is good idea. I will add this script soon.
Thanks.

**Comment by mrhut10** [comment]
Thank you, can you notify me when that's in the application?

**Comment by mrhut10** [comment]
How come you closed it also @restmount
