### ISSUE TITLE
Issue about change domain name from localhost to real domain

### ISSUE THREAD

**Issue by playerthong** [cezerin/cezerin#429]
Hi everyone,
I 'm facing one issue relate to Ajax in Cezerin. 

http://prntscr.com/j85sft
http://prntscr.com/j85sft
"Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin"

I changed "localhost" to "katyclothing.com" and port 3000 -> 80 in server.js .But I always see this issue . 

Could you mind help me this bug?

**Comment by restmount** [comment]
@playerthong 
Check this config files https://github.com/cezerin/docker-cezerin/tree/master/images/0.33.0/config

**Comment by playerthong** [comment]
@restmount r
I check this config . I see this config for docker. Could I use them for install cezerin in Linux ?
my admin.js => http://prntscr.com/j8g888

server.js => http://prntscr.com/j8g8e8

store.js => http://prntscr.com/j8g8iq


When I run "npm run start"
I see this  bug
http://prntscr.com/j8g7qx

The bug still happen => http://prntscr.com/j8g8w4

**Comment by anthlasserre** [comment]
@playerthong Can you show us your collection "settings" in "shop" mongodb database?
Maybe try to solve it with my answer here #439

**Comment by sonufrienko** [comment]
Issue fixed here https://github.com/cezerin/cezerin/commit/aaf5171e0fe294ea0cf27da627a383e77eca9c6a
Now domain can be empty.
