### ISSUE TITLE
Starting App (NPM Start)

### ISSUE THREAD

**Issue by ericsteinman** [cezerin/cezerin#439]
Hello! I am fairly new to all of this so forgive me for my ignorance. This platform looks like it would be incredibly helpful for a project I am working on to create a ecommerce store utilizing MERN.

I have followed the Getting Started steps multiple times and have yet to get this running on my computer successfully. Any help is greatly appreciated. :)

**My Info/Environment**
- macOS 10.12.6
- npm v5.6.0
- MongoDB version v3.6.3
- Node v8.11.1

**Flow**
- git clone
- cd cezerin
- npm install
- npm run build
- npm start

Here is a screenshot of when i run `npm start`

<img width="736" alt="screen shot 2018-05-02 at 8 01 03 pm" src="https://user-images.githubusercontent.com/32208280/39556255-ac987eb0-4e44-11e8-897c-875d06a58015.png">

**Debug.log**

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'start-api' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.11.1
> 4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
> 5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
> 6 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
> 7 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
> 8 verbose lifecycle cezerin@0.33.0~start-api: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/School/Documents/Homework/Project 3/cezerin/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/School/Documents/Homework/Project 3/cezerin/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin
> 9 verbose lifecycle cezerin@0.33.0~start-api: CWD: /Users/School/Documents/Homework/Project 3/cezerin
> 10 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
> 11 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
> 12 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
> 13 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid cezerin@0.33.0
> 15 verbose cwd /Users/School/Documents/Homework/Project 3/cezerin
> 16 verbose Darwin 16.7.0
> 17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-api"
> 18 verbose node v8.11.1
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
> 22 error Exit status 1
> 23 error Failed at the cezerin@0.33.0 start-api script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by chrisrijos** [comment]
Make sure you are using node version at least 8. Reclone and redo the process.

**Comment by ps011** [comment]
I'm facing the same issue on node v8.11

**Comment by ps011** [comment]
@ekarailiev  The problem will persist even after importing the seed data, you need to change some values in the config/* directory. Replace "localhost:3000" and "localhost:3001" with your domain name. This worked for me.

**Comment by HaswinVidanage** [comment]
This issue still exists. Any help is appreciated.

> Windows 10
> node v 8.9.0
> npm  v 5.5.1
> mongo v 3.6

**Comment by anthlasserre** [comment]
If you installed Cezerin App with Github:
- First have a look if you have the ".babelrc" file.
- Second just add this to your "webpack.config.admin.js" & "webpack.config.store.js":
`performance: {
    hints: false
  },`
- Next do a `npm install`
- Next `npm run build`
- Next `npm start`

It worked for me

**Comment by amp9020** [comment]
its your Webpack.

**Comment by sonufrienko** [comment]
@HaswinVidanage 
please check the latest version from GitHub.

**Comment by sulaiman21** [comment]
I am using latest version but i am facing "cezerin@0.33.0 start: `concurrently npm:start-*`" this problem. I have installed all dependencies. But i don't know why i am facing this problem.
