### ISSUE TITLE
Port missing in product image URL

### ISSUE THREAD

**Issue by danielInLionsDen** [cezerin/cezerin#441]
Product images do not appear in GitHub store pages.    Port number (3000) is missing from image URL.

Works for Docker store only because port=80.

**Comment by rifaia** [comment]
In the admin dashboard under general settings include port number in the domain field and check

**Comment by sonufrienko** [comment]
Issue fixed here https://github.com/cezerin/cezerin/commit/aaf5171e0fe294ea0cf27da627a383e77eca9c6a
Now domain can be empty. Product iamge will be relative.
