### ISSUE TITLE
How to deploy without docker?

### ISSUE THREAD

**Issue by mkouchi** [cezerin/cezerin#442]
I want to deploy cezerin without docker. with tools :pm2, nginx, git hooks. but I experience difficulties. please guide about this.
How to map localhost:3000 and localhost:3001 with the domain name using nginx reverse-proxy.

**Comment by sonufrienko** [comment]
Hi @mkouchi 
you need:
1. change config files
2. setup Nginx

Files from Docker image can help you.

**Comment by mkouchi** [comment]
Thanks
but what are that changes? 
I need that.

**Comment by amp9020** [comment]
@mkouchi ,as  @sonufrienko mentioned, docker image for reference, and  please update your files in config/*js to be reflective to your single domain.  run npm build, curl to test.

**Comment by mkouchi** [comment]
Ok, Thanks.

**Comment by sonufrienko** [comment]
Hi,
please, check new doc [How to deploy a Cezerin on Ubuntu 18.04.1 (from GitHub)
](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md).
