### ISSUE TITLE
Product tab is blanked

### ISSUE THREAD

**Issue by DevKaranMehta** [cezerin/cezerin#444]
My products collection is empty but,when i try to open product tab it looks blanked screen.
http://localhost:3001/api/v1/products?discontinued=false&fields=id%2Cname%2Ccategory_id%2Ccategory_ids%2Ccategory_name%2Csku%2Cimages%2Cenabled%2Cdiscontinued%2Cstock_status%2Cstock_quantity%2Cprice%2Con_sale%2Cregular_price%2Curl&limit=50&offset=0&search=&sort=name

![photo_2018-05-05_02-10-13](https://user-images.githubusercontent.com/35876864/39651952-811193a0-5009-11e8-876a-102fdd348102.jpg)

**Comment by dimeros** [comment]
Are you sure that you use the correct mongo version >=3.2?

**Comment by ampsarfraz** [comment]
![issue](https://user-images.githubusercontent.com/23452573/40696071-bd9643a2-63e1-11e8-85d0-9a6773b76b7a.png)
hi We are getting the same error too , when we deploy the Docker image. Can you please let us know how to resolve this issue?

**Comment by ampsarfraz** [comment]
![issue](https://user-images.githubusercontent.com/23452573/40696121-15d06c46-63e2-11e8-8c96-fa5e7be60d0a.png)

We are getting the same error when we deploy the docker image. Can you please let us know how to resolve this?

**Comment by sonufrienko** [comment]
Hi,
please, check new doc [How to deploy a Cezerin on Ubuntu 18.04.1 (from GitHub)
](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md).
