### ISSUE TITLE
Using Cezerin for multi-vendor marketplace?

### ISSUE THREAD

**Issue by dalerka** [cezerin/cezerin#448]
Hi and thanks for great work! I wonder if it would be feasible to improve _Cezerin_, so it could be used as a solution for _multi-vendor marketplace_? What challenges are there?

_Important:_ 
- Let sellers register and create/manage their own shop(s), i.e. list products per shop.
- Let sellers pay a marketplace fee (monthly) to make their shop(s) live (published & searchable).
- Let admins manage in (view, approve, suspend, block)
- Let admins create & control product schemas (i.e. categories and properties which sellers can choose from) 
- Let sellers assign "editors" (team-mates) for their shops. 

_Not important_ (i.e. not in near future): 
- Payments, shipping, orders from multiple vendors. 

The goal is to let offline retailers simply showcase their products.

**Comment by sonufrienko** [comment]
@dalerka 
Yes, Cezerin can be used as a multi-vendor marketplace after adding new features.
I love Cezerin for its API-centric architecture.
