### ISSUE TITLE
Why link admin page not request login ?

### ISSUE THREAD

**Issue by ngocdtph03070** [cezerin/cezerin#449]
After config and run project i try acess to localhost:3000/admin but not request login and run to dashboard

**Comment by lalitdashora** [comment]
Make sure you have changed the developer mode to false in config/admin.js file.

**Comment by ghost** [comment]
Buenas tardes. yo no estoy trabajando el proyecto con docker. hice los pasos para cuando digite localhost:3000/admin me saliera el login, pero no sale.  me podrías ayudar, Gracias. te lo agradecería

**Comment by Zombiemx** [comment]
Tal vez tienes que hacer el npm build de nuevo
