### ISSUE TITLE
Uploaded images dont show, not solved in latest image

### ISSUE THREAD

**Issue by jmuchaxo** [cezerin/cezerin#450]
Hello I find the bug Uploaded images don't show was solved sometime last month.
I check docker images and get 
cezerin/cezerin     latest              b3dc1e84ab06        2 months ago

How do you recommend to update the docker image or get latest source code?
it does not seem to be controlled by git

**Comment by bsmithEG** [comment]
Also experiencing this issue

**Comment by ibxccc123** [comment]
Fixed the above issue by initializing the data in https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md in the shop database in MongoDB.  I was doing it incorrectly by initializing the data in the shell and creating a new database.

**Comment by jjgumucio** [comment]
@ibxccc123 could you elaborate a little more please?
I think I did the same thing you mention but, it didn't work (Initializing the data on the "shop" database).

All help would be really appreciated.

**Comment by anthlasserre** [comment]
Look at the domain parameter on your "shop" mongodb database.
If you're using a port like 3000, be sure your domain parameter is: `http://localhost:3000`.
@ibxccc123 You can edit it from admin side (Settings/General/Domain) or directly in your mongodb database with mongo client `mongo`.
`use shop`
`db.settings.update({domain: "http://localhost:3000"})`

**Comment by jmuchaxo** [comment]
Thank you,currently i stopped using the product and unpaused my shopify storeI may need cezerin againthank you  I will write this down.
    On Thursday, 14 June 2018, 00:05:22 WEST, Anthony LASSERRE <notifications@github.com> wrote:  
 
 
Look at the domain parameter on your "shop" mongodb database.
If you're using a port like 3000, be sure your domain parameter is: http://localhost:3000.
@ibxccc123 You can edit it from admin side (Settings/General/Domain) or directly in your mongodb database with mongo client mongo.
use shop
db.settings.update({domain: "http://localhost:3000"})

**Comment by jjgumucio** [comment]
@anthlasserre Wow! so simple!
Thanks, problem solved!

**Comment by anthlasserre** [comment]
@jmuchaxo

**Comment by jjgumucio** [comment]
Well, I'm having the same issue again but this time is on the deployed version of my "custom" cezerin project.
I copied the docker file from the original one except that it is now pulling the app code from my forked repo. Everything else is the same.
The logo and product images are not loading. I have tried changing the domain to use localhost:3000, localhost:4000, and the VM ip but nothings seems to work.

Any advise on this?
Again, all tips/recommendations/help would be greatly appreciated.

**Comment by czhoffmann23** [comment]
Guys I’m also working with docker in a deployed version and images are not shown. Help please! D:

**Comment by jjgumucio** [comment]
Quick update! 
We setup a domain for our deployment and use it on the store settings: Good news and bad news.
Good: Product images are loading fine.
Bad: Logo image is not being displayed yet.

Hope this helps.

**Comment by jjgumucio** [comment]
@czhoffmann23 did you get a "real" domain for your site? 
I was having the same problem until I got a domain setup. Then, just setting the "domain" field on the settings page made images work except for the main logo (the one on the header).

**Comment by sonufrienko** [comment]
Issue fixed here https://github.com/cezerin/cezerin/commit/aaf5171e0fe294ea0cf27da627a383e77eca9c6a
Now domain can be empty. Product image will be relative.
