### ISSUE TITLE
Stripe Payment

### ISSUE THREAD

**Issue by 2monkey** [cezerin/cezerin#454]
Is there any implementation for the Stripe API ? 
Currently there is only Paypal

**Comment by dchilders21** [comment]
I too was looking to implement the Stripe API.  I began using the below implementation but ran into a few issues.  Having trouble calling in the <script src="https://js.stripe.com/v3/"></script> on the checkout page and having the StripeProvider component read it.  How did you get the Paypal option working?  I don't see it in the admin section.

https://github.com/stripe/react-stripe-elements#then-load-stripejs-in-your-application

**Comment by sonufrienko** [comment]
Hi!
In a week or two I also will try to add Stripe.
@dchilders21 if you implement Stripe, pls add a PR.

**Comment by 2monkey** [comment]
@dchilders21 
you have to implement the SSR Method.
https://github.com/stripe/react-stripe-elements#server-side-rendering-ssr

**Comment by 2monkey** [comment]
@sonufrienko  any success?

**Comment by mrhut10** [comment]
I've been watching this project for few months and waiting for you to have stripe support. Had figured would have been nice to do it but haven't had time :(

Any feedback on your attempt encase someone has a chance to help?

**Comment by abettarini** [comment]
I've started to add Stripe Elements a few days ago. I'm at a good point to have it working. 

I'll keep you up-to-date

**Comment by RoraxHan** [comment]
hello, stripe payment integrated ?
otherwise..
@abettarini : can you send me the source that is implemented stripe?
