### ISSUE TITLE
mongo => MySQL

### ISSUE THREAD

**Issue by 2monkey** [cezerin/cezerin#456]
is it possible to change the database to mysql (or something else) ?

**Comment by mihado** [comment]
+1 for PostgreSQL as well.

**Comment by sonufrienko** [comment]
I work with MS SQL Server more than 6 years. I am a big fan of SQL.
But now I like to work with a document-oriented database. Faster development, faster changes, less breaking changes.
+ MongoDB.

**Comment by mihado** [comment]
@sonufrienko If you haven't already, I recommend trying Postgres JSON type if you need to store document https://blog.codeship.com/unleash-the-power-of-storing-json-in-postgres/

It should be flexible enough for product schema, and you don't have to worry about data consistency.

**Comment by sonufrienko** [comment]
@mihado 
Thanks. I'll read it.

**Comment by dsp1589** [comment]
any update or anyone succeeded in setting up relational DB and detached mongo db in cezerin? Is there any future plan to support relational database like mysql and mariadb

**Comment by sonufrienko** [comment]
@dsp1589 
Any Service in Cezerin API can be rewritten to use a different type of database.
Some can use MongoDB, another PostgreSQL or Redis, etc.
Almost all services are independent.

On the current stage, it's more important to refactor all code and cover with tests :wink:

**Comment by rameshsrinivasan** [comment]
+1 for MySQL
