### ISSUE TITLE
Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ponkster** [cezerin/cezerin#458]
I got problem when I tried to build from github, based on instruction in [https://github.com/cezerin/cezerin/blob/master/docs/getting-started.md#1-installation](url). Below is the error message (I run **npm run build:watch**):

> Entrypoint app [big] = admin-assets/js/vendor-7d51634c75b31e9e0e3d.js admin-assets/js/app-bb324556ea822f9a0f62.js admin-assets/css/bundle-254b526d49c54b11b0ebaccec844088a.css
[./src/admin/client/app.js] 6 KiB {app} [built]
[./src/admin/client/index.js] 1.88 KiB {app} [built]
[./src/admin/client/lib/apiWebSocket.js] 3.02 KiB {app} [built]
[./src/admin/client/lib/auth.js] 2.85 KiB {app} [built]
[./src/admin/client/lib/settings.js] 51 bytes {app} [built]
[./src/admin/client/modules/pages/reducer.js] 908 bytes {app} [built]
[./src/admin/client/modules/productCategories/reducer.js] 2.12 KiB {app} [built]
[./src/admin/client/modules/products/reducer.js] 4.42 KiB {app} [built]
[./src/admin/client/modules/settings/actionTypes.js] 2.76 KiB {app} [built]
[./src/admin/client/modules/settings/actions.js] 17.1 KiB {app} [built]
[./src/admin/client/modules/settings/reducer.js] 3.86 KiB {app} [built]
[./src/admin/client/rootReducer.js] 1.7 KiB {app} [built]
   [0] multi react react-dom react-redux redux-thunk react-router-dom react-dropzone redux redux-form redux-form-material-ui material-ui 136 bytes {vendor} [built]
[./src/admin/client/routes/apps/index.js] 2.16 KiB {app} [built]
[./src/admin/client/routes/products/index.js] 1.19 KiB {app} [built]
    + 1410 hidden modules

>ERROR in ./src/admin/client/modules/customers/edit/components/style.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .button {
|   margin-left: 12px;
| }
 @ ./src/admin/client/modules/customers/edit/components/details.js 17:13-35
 @ ./src/admin/client/modules/customers/edit/index.js
 @ ./src/admin/client/routes/customers/edit.js
 @ ./src/admin/client/app.js
 @ ./src/admin/client/index.js

>ERROR in ./src/admin/client/modules/apps/account/components/style.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .button {
|   margin-left: 12px;
| }
 @ ./src/admin/client/modules/apps/account/components/details.js 17:13-35
 @ ./src/admin/client/modules/apps/account/index.js
 @ ./src/admin/client/routes/apps/index.js
 @ ./src/admin/client/app.js
 @ ./src/admin/client/index.js
> ....
   ....
   ....

>Child html-webpack-plugin for "admin/index.html":
     1 asset
    Entrypoint html-webpack-plugin for "admin/index.html" = admin/index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/admin/client/index.html] 4.71 KiB {html-webpack-plugin for "admin/index.html"} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {html-webpack-plugin for "admin/index.html"} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {html-webpack-plugin for "admin/index.html"} [built]
        + 1 hidden module

My Node version is ***v8.11.1***. What is the issue?

**Comment by anthlasserre** [comment]
@ponkster Maybe the same issue, look my answer on and try #439

**Comment by ponkster** [comment]
@anthlasserre thanks for your kind answer, I will try with your workaround, despite I strongly believe that it was because of extract-text-webpack-plugin incompatibilty with webpack 4

**Comment by sonufrienko** [comment]
We moved to **mini-css-extract-plugin**
Is it solved now?

**Comment by ponkster** [comment]
Hi @sonufrienko, yes it has been solved. After pulled the last update, the npm run build still produce the same error, until I commented this https://github.com/cezerin/cezerin/blob/bb72aa1be6269f3563b6bb2b4b8e9b322f33ad59/webpack.config.admin.js#L74 then the build run perfectly.

Thank you
