### ISSUE TITLE
How to edit server.js and other files after deploying to Docker ( Digital Ocean ) ?

### ISSUE THREAD

**Issue by viralpatel380** [cezerin/cezerin#472]

**Comment by mrhut10** [comment]
I'm no expert but you'd likely need to make the changes and then rebuild the docker image.

**Comment by mrhut10** [comment]
@viralpatel380 have you had any luck? might be worth reaching out to digital oceans support team, seeing your a customer my guess is they would be able to help. ( although i haven't used them myself. )

**Comment by jjgumucio** [comment]
Yes, you should have a Docker autobuild system up. That way, whenever you change your Dockerfile or you push new code to your repo (if you configure webhooks), the Docker image would build again.
Then, you would need to redeploy this new image.

Hope it helps.

**Comment by tigrankhachikyan** [comment]
1. `docker ps`
2.  `docker exec -it <mycontainer> bash`
so you would be able to change files inside docker container

**Comment by sonufrienko** [comment]
You can deploy from GitHub with easy.
Please, check new doc [How to deploy a Cezerin on Ubuntu 18.04.1 (from GitHub)
](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md)
