### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):

### ISSUE THREAD

**Issue by tcthtuananh** [cezerin/cezerin#473]
Binary found at D:\React\ecommerce\cezerin\node_modules\node-sass\vendor\win32-x64-59\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by lfurzewaddock** [comment]
Don't worry, [fsevents](https://github.com/strongloop/fsevents) provides native access to Mac OS-X FSEvents, so only works on Mac OS-X.

This is only a warning and as it is also an optional dependency, it is safe to ignore.

**Comment by tcthtuananh** [comment]
thanks

**Comment by JipingWang** [comment]
should not be "warning", cuz "warning" tells you need to concern that. should be like the following,
```
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
```
