### ISSUE TITLE
Question: Is there a way to manage a inventory for a product variation

### ISSUE THREAD

**Issue by tigrankhachikyan** [cezerin/cezerin#474]
Can I set a stock quantity for a variation and not for a product (from admin dashboard)

**Comment by tigrankhachikyan** [comment]
So can this issue be considered as a feature request?

**Comment by sonufrienko** [comment]
@tigrankhachikyan 
Yes, you can.
You can add product variant with options, sku, stock quantity, weight and price.

**Comment by tigrankhachikyan** [comment]
I see, thank you!
