### ISSUE TITLE
Docker image NGINX configuration

### ISSUE THREAD

**Issue by jjgumucio** [cezerin/cezerin#475]
Guys, can you show the NGINX configuration set up on the Docker image?

I'm currently using cezerin/latest with some custom extensions (basically a new version of the software) so the original docker images is not useful for our testing.

I would like to "reproduce" the docker image on a custom VM running Linux (Debian based).

Thanks in advance.

**Comment by Pedrock** [comment]
It's available here: https://github.com/cezerin/docker-cezerin/tree/master/images/0.33.0/nginx

**Comment by jjgumucio** [comment]
Thanks!
