### ISSUE TITLE
setup issues: Not able to Browse the store

### ISSUE THREAD

**Issue by MAJIDNISAR** [cezerin/cezerin#478]
Hi thanks in advance
i have configured the store according to the documentation
but i am not able to browse the store . need some help
console output:
![image](https://user-images.githubusercontent.com/3784652/41796765-57c08644-7685-11e8-9279-61f0b28ae6d7.png)
while as in browser:
![image](https://user-images.githubusercontent.com/3784652/41796827-7501a094-7685-11e8-889b-f546ba385999.png)

**Comment by freakk101** [comment]
it seems like you did not run build.

try, 
npm install
npm run build
npm start
