### ISSUE TITLE
Images are not loading in deployed version using Docker

### ISSUE THREAD

**Issue by ClementeSerrano** [cezerin/cezerin#481]
I copied the docker file from the original one except that it is now pulling the app code from my forked repo. Everything else is the same.

The logo and product images are not loading. I have tried changing the domain to use localhost:3000, localhost:4000, and the VM ip but nothings seems to work.

**Comment by sonufrienko** [comment]
Issue fixed here https://github.com/cezerin/cezerin/commit/aaf5171e0fe294ea0cf27da627a383e77eca9c6a
Now domain can be empty. Product image will be relative.
