### ISSUE TITLE
Question: How to manage admin panel with only one email (admin's emails)

### ISSUE THREAD

**Issue by tigrankhachikyan** [cezerin/cezerin#483]
I want to manage the admin only with one email. So no one else can request a login url.

Best Regards.

**Comment by sonufrienko** [comment]
@tigrankhachikyan 
API will check, does email exists in tokens collection when someone request login URL.
So no one can request a login URL.

**Comment by tigrankhachikyan** [comment]
Oh I see. 
May be I'm doing something wrong, but.
here is my steps.
1. /admin is available from Chrome and Firefox
2. Logout from Chrome (/admin/logout)
3. Request url for another email (/admin/login)
3.1 it says Access denayd
4. /admin is still available in Firefox and Chrome

note, no access tokens are created from admin panel.Am I missing something?

http://178.128.163.248 for my example

Thanks in advance.

**Comment by sonufrienko** [comment]
@tigrankhachikyan 
You need to disable **developer mode** in config files.
https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-16-04.md#7-turn-off-developer-mode

**Comment by tigrankhachikyan** [comment]
I did all these steps, but `/admin` url is still available.

Add access token in Dashboard or MongoDB
Set SMTP server from Dashboard or in config/server.js
Remove developerMode from config/server.js
Remove developerMode from config/admin.js
npm run build inside Cezerin container
pm2 reload api inside Cezerin container

**Comment by tigrankhachikyan** [comment]
ok, sorry, need to restart docker container as well
Closing.
Thank you!
