### ISSUE TITLE
When restmount come back

### ISSUE THREAD

**Issue by channingbox** [cezerin/cezerin#484]
I think he is busy.

**Comment by sonufrienko** [comment]
@channingbox 
As I understand now he is busy.
Until he back to us, I'll support Cezerin.

**Comment by mrhut10** [comment]
@channingbox @sonufrienko while he is busy do we think anyone can look at the pr's i submitted?

- #477 which will allow windows developers to use the project ( including myself )
- #476 which is a more convenient way of setting just pasting in a connection string from your hosted mongoDB ( although might be similar to #434 )

**Comment by sonufrienko** [comment]
@mrhut10 
I'll check PR's.

**Comment by mrhut10** [comment]
Thank you @sonufrienko

**Comment by sonufrienko** [comment]
I got an email from Restmount. He is busy with his work.
I'll support Cezerin.

**Comment by mrhut10** [comment]
sweet!!, thanks for merging my pr #477 

nice
