### ISSUE TITLE
Start API fails with Exit Status 1

### ISSUE THREAD

**Issue by amey10794** [cezerin/cezerin#493]
Ubuntu 16.04
node v8.9.3
mongo 5.5.1

**Error:**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin@0.33.0 start-api: `node src/api/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin@0.33.0 start-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amey/.npm/_logs/2018-07-12T16_37_40_370Z-debug.log

**Debug Log:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start-api' ]
2 info using npm@5.5.1
3 info using node@v8.0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start-api' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start-api: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/home/amey/google-cloud-sdk/bin:/home/amey/bin:/home/amey/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/amey/My
9 verbose lifecycle cez0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start-api' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start-api: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/home/amey/google-cloud-sdk/bin:/home/amey/bin:/home/amey/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/amey/My
9 verbose lifecycle cezerin@0.33.0~start-api: CWD: /home/amey/MITYO
10 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
11 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
13 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /home/amey/MITYO
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-api"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start-api script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]erin@0.33.0~start-api: CWD: /home/amey/MITYO
10 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
11 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
13 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /home/amey/MITYO
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-api"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start-api script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]9.3
4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start-api: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/amey/MITYO/node_modules/.bin:/home/amey/google-cloud-sdk/bin:/home/amey/bin:/home/amey/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/amey/My
9 verbose lifecycle cezerin@0.33.0~start-api: CWD: /home/amey/MITYO
10 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
11 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
13 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /home/amey/MITYO
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-api"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start-api script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have initialized Mongodb with the default collections but I deleted the default documents inside the pages collection and added custom documents. Other than the pages collection I have made sure all the other default collections are initialized as mentioned on the cezerin mongodb page. From my observation, I usually get this error when I try to access the Mongodb database using Express/Node.
I appreciate your help.Thanks

**Comment by Peppuz** [comment]
Same problem here! I'll try to get the answer

**Comment by sonufrienko** [comment]
@amey10794 
Please, show me 
1. MongoDB connection
1. all your commands to start
2. console errors when you start

**Comment by jallkay** [comment]
Same issue here!

**Comment by jallkay** [comment]
Follow up: I resolved mine by updating my Node

**Comment by Heartz66** [comment]
You can solve this by updating your Node.js to the latest version (v10.6.0) and removing node_modules and doing npm install again.

**Comment by sonufrienko** [comment]
Change Node version to 10 isn't a solution. Need more details.

**Comment by amey10794** [comment]
@sonufrienko 

1.  MongoDB connection
MongoClient.connect("mongodb://localhost:27017/shop", function (err, db) {
   
     if(err) throw err;

//othermongodb commands for reading and writing
                
});

2. Start Commands: 
"start": "npm run compile | ./node_modules/.bin/babel theme/src -d theme/dist --quiet | npm run start-api | npm run start-store | ./node_modules/.bin/webpack --config webpack.config.store.js --mode development --watch | ./node_modules/.bin/webpack --config webpack.config.admin.js --mode development --watch"

3. Console errors are same as above:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin@0.33.0 start-api: node src/api/server/index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin@0.33.0 start-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/amey/.npm/_logs/2018-07-12T16_37_40_370Z-debug.log

**Comment by amey10794** [comment]
@sonufrienko  were you able to get a solution for the issue? 
Thanks for your help

**Comment by heartstchr** [comment]
@amey10794  If this occurred after the pull from upstream then the following step will solve the problem
rm -rf node_modules 
node -v
output: v8.X
npm install

**Comment by sonufrienko** [comment]
@amey10794 
I have no errors on the project start.

Double check your code:
```Start Commands:
"start": "npm run compile | ./node_modules/.bin/babel theme/src -d theme/dist --quiet | npm run start-api | npm run start-store | ./node_modules/.bin/webpack --config webpack.config.store.js --mode development --watch | ./node_modules/.bin/webpack --config webpack.config.admin.js --mode development --watch"```
