### ISSUE TITLE
admin dashboard accessible even after development mode is set to false

### ISSUE THREAD

**Issue by freakk101** [cezerin/cezerin#494]
Any clue why admin as mode is accessible even after development mode is set to false, is it a default behaviour or authentication of admin dashboard is in roadmap ?

**Comment by sonufrienko** [comment]
@freakk101 
Please, follow this doc https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-16-04.md#7-turn-off-developer-mode

1. change mode for dashboard and API
2. re-build
3. re-run
