### ISSUE TITLE
Option for building url that would follow complete chain of parent categories

### ISSUE THREAD

**Issue by lefcf** [cezerin/cezerin#497]
Hello guys, great work.

- for situation Category2 in Category1 in Category0 and Product2 in Category2
It seems like url of category2 is 
urlShop/category2slug 
urlShop/category2slug/product2slug

If not too demanding, think of putting an option for this way, as well:
urlShop/category0slug/category1slug/category2slug
urlShop/category0slug/category1slug/category2slug/product2slug.

**Comment by sonufrienko** [comment]
Too deep URL is not recommended to SEO.
I think the current URL model is the best practice.
