### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by FaRzad-845** [cezerin/cezerin#502]
how can we make all components and the code RTL( right to left) ... ?
ex : Arabic website ... 
💯

**Comment by sonufrienko** [comment]
Hi @FaRzad-845 
1. /theme/assets/index.html - <html dir="rtl" lang="he">
2. /theme/assets/css/theme.scss - add some styles
3. sometimes replace solumns in code

I have successfully built an RTL web store with Cezerin.

**Comment by mjmaahs** [comment]
Hi,
can i have a more detailed step for rtl ?
