### ISSUE TITLE
DeprecationWarning: collection.count is deprecated

### ISSUE THREAD

**Issue by sonufrienko** [cezerin/cezerin#506]
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

**Comment by edenmw** [comment]
My approach
\node_modules\mquery\lib\collection\node.js:50
NodeCollection.prototype.count = function(match, options, cb) {
  this.collection.count(match, options, cb);
};
=> NodeCollection.prototype.countDocuments = function(match, options, cb) {
  this.collection.countDocuments(match, options, cb);
};

\node_modules\mongoose\lib\query.js:1950
this._collection.count(conds, options, utils.tick(callback));
=> this._collection.countDocuments(conds, options, utils.tick(callback));
