### ISSUE TITLE
npm ERR! missing script: setup [docker/ubuntu]

### ISSUE THREAD

**Issue by itsmidnightyo** [cezerin/cezerin#524]
I am currently setting up a little shop for a client and following the [docker tutorial](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-16-04.md), an error has been encountered and I am not sure where to go from here or how to fix it.. 😭 

When I was executing the command to Step 6, it gave me this error:
`root@ubuntu-s-1vcpu-1gb-sfo2-01:~# sudo docker exec store bash -c "npm run setup"
npm ERR! missing script: setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-28T17_47_23_710Z-debug.log`

When I go to the root folder in FileZilla of my VPS, there is no trace of an npm folder with a log so I'm not really sure what went wrong or what I can do.

Thanks in advanced if anyone is able to help me! 👍 💯

**Comment by sonufrienko** [comment]
Hi @itsmidnightyo 
Docker image is outdated. I'll update it when @restmount send me access.
For now, you can setup Cezerin from GitHub.

I'll find a time and write a manual "How to install Cezerin from GitHub".

**Comment by itsmidnightyo** [comment]
Thanks @sonufrienko !
I thought I was doing something incorrectly. 💜 

So, once I set it up from GitHub, how will I be able to distribute it to the VPS succesfully w/o Docker?
or can I make a Docker image myself? :)

**Comment by Oliverhowden** [comment]
Any luck with this? I've tried installing from Github though getting a few weird database issues so would love the Docker version!

**Comment by itsmidnightyo** [comment]
@Oliverhowden,
I've actually installed it successfully on my DigitalOcean VPS running Ubuntu 16.04! Although it took me a while to figure it out and configure nginx, I got it working! 💯 

What are you looking to achieve?
In my opinion, I find it easier to deploy on your website first and work from there so you don't have to worry about messing something up in the long run.

**Comment by sonufrienko** [comment]
Hi,
please, check new doc [How to deploy a Cezerin on Ubuntu 18.04.1 (from GitHub)
](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md)
