### ISSUE TITLE
Server not working on VPS (Website won't respond)

### ISSUE THREAD

**Issue by SimDoes** [cezerin/cezerin#525]
I'm on Google Cloud using Ubuntu 18.04. I installed everything happily (after like a good 2hrs of errors).
Here's the installation I did in a few lines for anyone having issues on Ubuntu. *Edit: don't run both `pm2` and `node start` I recommend running just pm2 instead.
```shell
sudo -s
sudo apt-get update ; sudo apt-get upgrade;curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - ; sudo apt-get install -y nodejs;sudo apt install -y mongodb; mongo
use shop
//ctrl + c
git clone https://github.com/cezerin/cezerin.git cezerin;cd cezerin;sudo npm install;sudo npm run build;sudo npm run setup;npm install pm2 -g;pm2 start process.json
npm start //use when you don't want to run pm2
```

Anyway I start npm and it says it's running on localhost, but I don't know how to make it work as a website.
I tried doing custom firewall rules on Google Cloud and changing the config files in /config and still nothing. It just says timed out on my browser. Any help would be appreciated.

Edit: I did wget localhost:3000 and got a successful reply. It seems that it only works on localhost. I will update this if I find a way to make it work with an ip. If anyone could help that would be appreciated.

**Comment by amp9020** [comment]
Please edit your config/*.js file , run npm run build and then start the app again.

**Comment by SimDoes** [comment]
@amp9020 what ip do I put where? and should I change the store.js and admin.js config aswell?

**Comment by amp9020** [comment]
@SimDoes yes modoify the js files.  you can put whatever IP you want or a hostname.  i personally would do reverse-proxy and do proxy-pass on the ports and leave it as is.

**Comment by sonufrienko** [comment]
Hi,
please, check new doc [How to deploy a Cezerin on Ubuntu 18.04.1 (from GitHub)
](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md)
