### ISSUE TITLE
build:watch syntax errors

### ISSUE THREAD

**Issue by ceracera** [cezerin/cezerin#530]
When running `npm run build:watch` I get a lot of errors related to JSX. It's like this:

`[compile] [themeWatcher]   3 | const InputField = field => (
[compile] [themeWatcher] > 4 |  <div className={field.className}>
[compile] [themeWatcher]     |  ^                                                                
[compile] [themeWatcher]   5 |          <label htmlFor={field.id}>                                                   
[compile] [themeWatcher]   6 |                  {field.label}                                                                
[compile] [themeWatcher]   7 |                  {field.meta.touched &&                                               
[compile] [themeWatcher] SyntaxError: theme/src/components/checkoutForm/paymentForm/LiqPay.js: Unexpected token (9:11) 
[compile] [themeWatcher]    7 |         }    `

Why is that happening and how to fix it?

**Comment by sonufrienko** [comment]
Fixed.
