### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by themcguy** [cezerin/cezerin#532]
Every single time I run npm install on my ubuntu EC2 instance, it hangs. Any idea why?? Frustrating to wait for hours with nothing happening..

**Comment by sonufrienko** [comment]
Hi @themcguy 
Any logs?

**Comment by themcguy** [comment]
It seems to have finished now. Not sure if I just didn't wait long enough or what. I also deleted node_modules and package-lock.json. I am now getting the following errors:

```
ERROR in multi theme
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin'
 @ multi theme theme[0]

ERROR in ./src/store/client/index.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/client'
 @ ./src/store/client/index.js 21:13-29
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/search.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/search.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/notfound.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/notfound.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/checkoutSuccess.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/checkoutSuccess.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/index.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/index.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/page.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/page.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/product.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/product.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/category.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/category.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/shared.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/shared.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js

ERROR in ./src/store/shared/containers/checkout.js
Module not found: Error: Can't resolve 'theme' in '/home/ubuntu/cezerin/src/store/shared/containers'
 @ ./src/store/shared/containers/checkout.js 17:13-29
 @ ./src/store/shared/app.js
 @ ./src/store/client/index.js
 @ multi babel-polyfill ./src/store/client/index.js
```

**Comment by sonufrienko** [comment]
@themcguy 
first of all, check this [new guide](https://github.com/cezerin/cezerin/blob/master/docs/how-to-deploy-a-cezerin-on-ubuntu-18-04-1-github.md)

Do you build it?
```
npm run build
```

**Comment by themcguy** [comment]
Hi. yes, I ran ```npm run build``` and that is what produced the above.

I don't know how to use docker. I would like to use an alternative if possible?

I'm running Ubuntu 16.04.5

**Comment by sonufrienko** [comment]
@themcguy 
What is your environment?
Node version?
Do you use the latest version of Cezerin?

**Comment by themcguy** [comment]
Hi, can you be a little more specific when you say "environment"?

ubuntu 16.04
node v10.0.0
npm v5.6.0
mongo db version v2.6.10

I pulled Cezerin from master branch.

Let me try the new guide. Does it work the same for Ubuntu 16.04?

**Comment by sonufrienko** [comment]
Node v10 can cause and error.
1. try a new guide
2. try to use Node v8

**Comment by themcguy** [comment]
Ok, trying now.

When you say "Generate new values for secret keys", how do you recommend doing that?

**Comment by sonufrienko** [comment]
I use LastPass -> Generate Secure Password

**Comment by themcguy** [comment]
Thanks.
I have run through the steps in the "new guide" and I still get the same errors I pasted above. The only difference is that my nginx version doesn't match but I feel like that should not matter. Additional logging:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cezerin@0.33.0 webpack:store: `webpack --config webpack.config.store.js --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 webpack:store script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_312Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cezerin@0.33.0 theme:build: `babel theme/src -d theme/dist --presets react --plugins transform-class-properties --quiet && npm run webpack:store`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 theme:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_325Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cezerin@0.33.0 build: `npm run compile && npm run theme:build && npm run webpack:admin`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cezerin@0.33.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_337Z-debug.log
```

**Comment by ldragos1** [comment]
> Thanks.
> I have run through the steps in the "new guide" and I still get the same errors I pasted above. The only difference is that my nginx version doesn't match but I feel like that should not matter. Additional logging:
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! cezerin@0.33.0 webpack:store: `webpack --config webpack.config.store.js --mode production`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the cezerin@0.33.0 webpack:store script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_312Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! cezerin@0.33.0 theme:build: `babel theme/src -d theme/dist --presets react --plugins transform-class-properties --quiet && npm run webpack:store`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the cezerin@0.33.0 theme:build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_325Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! cezerin@0.33.0 build: `npm run compile && npm run theme:build && npm run webpack:admin`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the cezerin@0.33.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ubuntu/.npm/_logs/2018-08-06T15_51_49_337Z-debug.log
> ```

@themcguy have you found a solution?
