### ISSUE TITLE
Is it possible to make variant function like this

### ISSUE THREAD

**Issue by yangjiamu** [cezerin/cezerin#534]
![variant](https://user-images.githubusercontent.com/7434540/43748362-bd49c0c4-9a21-11e8-9fec-898690510a30.png)

**Comment by sonufrienko** [comment]
Hi @yangjiamu 
It's possible but need to do:
1) add an image to an option
2) render options as Radio Buttons

**Comment by yangjiamu** [comment]
@sonufrienko Ok, thanks, and i want to know if cezerin's variants will be planned to change like this in future?

**Comment by sonufrienko** [comment]
@yangjiamu 
It's hard to say.

**Comment by francescotaioli** [comment]
@yangjiamu hi, i want to achieve the same function. have you do it?

**Comment by freakk101** [comment]
> add an image to an option
> render options as Radio Buttons

what if we want to display the images associated to that option in gallery section ?
