### ISSUE TITLE
Issue with product image sizing on home page.

### ISSUE THREAD

**Issue by chrisrijos** [cezerin/cezerin#538]
If you add a product and add an image on desktop the image is way oversized. These values are being evaluated as null and the dom is assigning the css class Infinity. 

<div
className={`column is-${columnSizeOnMobile}-mobile is-${columnSizeOnTablet}-tablet is-${columnSizeOnDesktop}-desktop is-${columnSizeOnWidescreen}-widescreen is-${columnSizeOnFullhd}-fullhd ${product.stock_status}`}>

![image](https://user-images.githubusercontent.com/7758819/43804088-704235b0-9a60-11e8-8cfc-a3cebad44eac.png)

**Comment by sonufrienko** [comment]
Hi @chrisrijos 
Thanks.
