### ISSUE TITLE
Mongo DB connection Failed , App is not starting 

### ISSUE THREAD

**Issue by ghost** [cezerin/cezerin#566]
I,ve changed confing details in `server.js and server.production.js` files like this 

`const dbHost = process.env.DB_HOST || '255.255.255.255';
const dbPort = process.env.DB_PORT || 27017;
const dbName = process.env.DB_NAME || 'shop';
const dbUser = process.env.DB_USER || 'user';
const dbPass = process.env.DB_PASS || 'password';
const dbCred =
	dbUser.length > 0 || dbPass.length > 0 ? `${dbUser}:${dbPass}@` : '';

const dbUrl =
	process.env.DB_URL || `mongodb://${dbCred}${dbHost}:${dbPort}/${dbName}`;
`

And this is the output ,

> cezerin@0.33.0 start C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\cezerin
> concurrently npm:start-*

[start-api]
[start-api] > cezerin@0.33.0 start-api C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\cezerin
[start-api] > node -r esm src/api/server/index.js
[start-api]
[start-store]
[start-store] > cezerin@0.33.0 start-store C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\cezerin
[start-store] > node -r esm dist/store/server/index.js
[start-store]
[start-store] info: Store running at http://localhost:3000
[start-api] info: API running at http://localhost:3001
[start-api] error: MongoDB connection was failed: failed to connect to server [255.255.255.255:27017] on first connect [MongoNetworkError: connect EADDRNOTAVAIL 255.255.255

How can I fix this?

**Comment by zgelp** [comment]
What do you want to achieve with this? I belive you typed in the wrong IP address for database, MongoDB usually listens on 127.0.0.1:27017.

Anyway, I belive "Issues" thread in this repo is not for your problems setting up database and API, but rather for specific bugs dealing with this repo's code / implementation.

**Comment by ghost** [comment]
I raised this issue because documentation should be up to date, check configuration section yourself `DB_HOST=255.255.255.255 \` and I done this and its still not working, some one should look into this. 

MongoDB usually listens on 127.0.0.1:27017. but it's advised to cahnge these in env variables. 

This is an implementation issue and that is why this is in "Issues" thread. 

Let me know if you can help me to fix this , many thanks

**Comment by zgelp** [comment]
Changing db IP to **DB_HOST=255.255.255.255** is optional, on master branch there is this configuration in **server.production.js**:

`// config used by server side only
const dbHost = process.env.DB_HOST || '127.0.0.1';
const dbPort = process.env.DB_PORT || 27017;
const dbName = process.env.DB_NAME || 'shop';
const dbUser = process.env.DB_USER || '';
const dbPass = process.env.DB_PASS || '';
const dbCred =
	dbUser.length > 0 || dbPass.length > 0 ? `${dbUser}:${dbPass}@` : '';`

and it works out of the box, if you init mongodb with given script (`npm run setup`).
Also don't forget to start mongodb daemon with `sudo mongod`.

**Comment by ghost** [comment]
Thank you , it worked
