### ISSUE TITLE
How delete Disqus

### ISSUE THREAD

**Issue by noenteas** [cezerin/cezerin#574]
Hey, can help for delete this section "disqus"

![image](https://user-images.githubusercontent.com/30532126/45827175-815c0d80-bcbb-11e8-8972-ec4c328ad63b.png)

**Comment by freakk101** [comment]
in /theme/src/components/productDetails/index.js on line number 5 find and remove 
`import Disqus from '../comments/disqus';` 
& 
remove  line number 196 to 205 `{themeSettings.disqus_shortname &&
						themeSettings.disqus_shortname !== '' && (
							<section className="section">
								<div className="container">
									<Disqus
										shortname={themeSettings.disqus_shortname}
										identifier={product.id}
										title={product.name}
										url={product.url}
									/>`

**Comment by noenteas** [comment]
Thanks
