### ISSUE TITLE
How to customize code?

### ISSUE THREAD

**Issue by vctqs1** [cezerin/cezerin#576]
I want customize homeSlider.js. And run build:watch. But it not work.

I try to cosole.log something to check. But it not show. And Where file css can change

**Comment by hoflish** [comment]
Hi @vctqs1,
you can customize User Interface (theme) from _`[root_path]/theme`_ folder.

- under _`[root_path]/theme/src`_ , you find React components
- _`[root_path]/theme/assets/scss`_ contains `.scss` files

Hot reload not supported yet, so you need to restart store (`npm run start`) after each build.

**Comment by noenteas** [comment]
Where or how do you get themes that are compatible?
