### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by KristofferKay** [cezerin/cezerin#606]
When will there be a new commit? As the last one was somewhere in August. I dont hope this project is dead because i find it very interesting.

**Comment by theleolife** [comment]
@Dekto I don't know what happened but it seems the owners is not maintaining anymore, I hope I am wrong @restmount @sonufrienko it's really good project.

**Comment by neunygph** [comment]
@Dekto since the original creator is not here anymore, we made a new repository here. Everyone is welcome to join https://join.slack.com/t/caesarcommerce/shared_invite/enQtNTA0ODExMjIyNjU3LWRhNTM2YzQ4MzMwMjMzN2Y1ZTNmYTkzMWJiOTg5NmE3OGZmOWRlNzViMmQyOTM1NjZjOGNlMWUyNmU5MzJmNjE

**Comment by minhcasi** [comment]
Same questions @restmount @sonufrienko, I love this project but it seems there is no updated

**Comment by LuBuss** [comment]
There is a group of us maintaining a new branch of this repo at https://github.com/Cezerin2/cezerin2

**Comment by panique** [comment]
the demo is also dead for long time :/

**Comment by orar** [comment]
> @Dekto since the original creator is not here anymore, we made a new repository here. Everyone is welcome to join https://join.slack.com/t/caesarcommerce/shared_invite/enQtNTA0ODExMjIyNjU3LWRhNTM2YzQ4MzMwMjMzN2Y1ZTNmYTkzMWJiOTg5NmE3OGZmOWRlNzViMmQyOTM1NjZjOGNlMWUyNmU5MzJmNjE

Slack link is dead. Please fix
