### ISSUE TITLE
New repository

### ISSUE THREAD

**Issue by neunygph** [cezerin/cezerin#607]
Hi all, 
Since the original creator is not here anymore, we made a new repository here. Please note this new repository is not from the original project creator, it's formed by a group of people who want to keep working on this project. Everyone is welcome to join https://join.slack.com/t/caesarcommerce/shared_invite/enQtNTA0ODExMjIyNjU3LWRhNTM2YzQ4MzMwMjMzN2Y1ZTNmYTkzMWJiOTg5NmE3OGZmOWRlNzViMmQyOTM1NjZjOGNlMWUyNmU5MzJmNjE

New repository link : https://github.com/CaesarCommerce/CaesarCommerce

**Comment by anton6** [comment]
Sorry can you please clarify which is this one? https://github.com/Cezerin2/cezerin2

**Comment by neunygph** [comment]
That’s our new active repository.

Phuong Nguyen

On Dec 23, 2018, at 6:32 PM, anton6 <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry can you please clarify which is this one? https://github.com/Cezerin2/cezerin2
