### ISSUE TITLE
Security checklist

### ISSUE THREAD

**Issue by restmount** [cezerin/cezerin#73]
https://blog.risingstack.com/node-js-security-checklist/

**Comment by gazonas** [comment]
https://expressjs.com/en/advanced/best-practice-security.html

**Comment by gazonas** [comment]
Add Helmet package in Store

**Comment by restmount** [comment]
csrf and xsrf

**Comment by gazonas** [comment]
Chrome help to protect from CSRF. You need to use SameSite='strict' option for cookies.

**Comment by gazonas** [comment]
Cookies can be stolen or modified. So you need to do:
1. cookies should be signed
2. HttpOnly and Secure (HTTPS)
3. Think about infrastructure security
